import { withApiErrors } from '@/lib/api-errors';
import {NextResponse} from 'next/server';import {getSessionUser} from '@/lib/auth';import {licenseActionSchema,parseJson,revokeLicenseSchema} from '@/lib/validation';import {bindLicense,listUserLicenses,revokeLicense,startTrial} from '@/lib/licensing';import {createSecurityContext,enforceRateLimits,RATE_LIMITS,withAudit} from '@/lib/security';
export const dynamic='force-dynamic';
async function GETHandler(request){const user=await getSessionUser();if(!user)return NextResponse.json({success:false,message:'请先登录'},{status:401});const admin=new URL(request.url).searchParams.get('scope')==='admin';if(admin&&user.role!=='admin')return NextResponse.json({success:false,message:'仅管理员可查看全部授权'},{status:403});return NextResponse.json({success:true,licenses:listUserLicenses(user.id,{admin})});}
async function POSTHandler(request){const user=await getSessionUser(),context=createSecurityContext(request,user);const audited=(response,outcome,reasonCode,metadata={})=>withAudit(context,response,{eventType:'license.write',outcome,reasonCode,targetType:'license',targetId:metadata.licenseId,metadata});const limited=enforceRateLimits(context,'license.write',[{policy:RATE_LIMITS.licenseWrite,identifier:user?`user:${user.id}`:context.sourceHash}]);if(limited)return limited;if(!user)return audited(NextResponse.json({success:false,message:'请先登录'},{status:401}),'failure','UNAUTHENTICATED');const parsed=await parseJson(request,licenseActionSchema);if(!parsed.success)return audited(parsed.response,'failure','VALIDATION_ERROR');try{const license=parsed.data.action==='start_trial'?startTrial(user.id,parsed.data.productId):bindLicense(parsed.data.licenseId,user.id,parsed.data.bindingType,parsed.data.value);return audited(NextResponse.json({success:true,license,replayed:Boolean(license.replayed)},{status:license.replayed?200:201}),'success',license.replayed?'REPLAYED':parsed.data.action.toUpperCase(),{licenseId:license.id,productId:license.productId});}catch(error){const known={TRIAL_BUILD_UNAVAILABLE:['试用版正在准备中，当前暂不能申请试用',409],PRODUCT_UNAVAILABLE:['策略不可用',404],SELF_TRIAL:['不能试用自己发布的策略',409],TRIAL_DISABLED:['该策略未开放试用',409],VERSION_UNAVAILABLE:['该策略没有可试用版本',409],ALREADY_OWNED:['您已经永久拥有该策略',409],LICENSE_NOT_FOUND:['授权不存在',404],FORBIDDEN:['无权操作该授权',403],LICENSE_INACTIVE:['授权已过期或已撤销',409],REBIND_LIMIT:['换绑次数已达上限',409],REBIND_COOLDOWN:['换绑后需等待 7 天才能再次换绑',429]};if(known[error.message]){const [message,status]=known[error.message];return audited(NextResponse.json({success:false,message},{status}),'failure',error.message);}if(error.code==='SQLITE_CONSTRAINT_UNIQUE')return audited(NextResponse.json({success:false,message:'该试用或绑定已经存在'},{status:409}),'failure','DUPLICATE');return audited(NextResponse.json({success:false,message:'授权操作失败'},{status:500}),'failure','INTERNAL_ERROR');}}
async function PATCHHandler(request){const user=await getSessionUser(),context=createSecurityContext(request,user);const audited=(response,outcome,reasonCode,metadata={})=>withAudit(context,response,{eventType:'license.revoke',outcome,reasonCode,targetType:'license',targetId:metadata.licenseId,metadata});if(user?.role!=='admin')return audited(NextResponse.json({success:false,message:'仅管理员可撤销授权'},{status:user?403:401}),'failure','FORBIDDEN');const parsed=await parseJson(request,revokeLicenseSchema);if(!parsed.success)return audited(parsed.response,'failure','VALIDATION_ERROR');try{const license=revokeLicense(parsed.data.licenseId,parsed.data.reason,user.id);return audited(NextResponse.json({success:true,license,replayed:Boolean(license.replayed)}),'success',license.replayed?'REPLAYED':'REVOKED',{licenseId:license.id});}catch(error){if(error.message==='LICENSE_NOT_FOUND')return audited(NextResponse.json({success:false,message:'授权不存在'},{status:404}),'failure',error.message);return audited(NextResponse.json({success:false,message:'授权不可撤销'},{status:409}),'failure',error.message);}}

export const GET = withApiErrors(GETHandler, { route: '/api/licenses' });
export const POST = withApiErrors(POSTHandler, { route: '/api/licenses' });
export const PATCH = withApiErrors(PATCHHandler, { route: '/api/licenses' });
