"use client";

import { useCallback, useEffect, useState } from 'react';
import { ArrowUpRight, CheckCircle2, Clock3, Coins } from 'lucide-react';
import { apiFetch } from '@/lib/api-client';
import PointRechargePanel from './PointRechargePanel';
import PointHistory from './PointHistory';

const labels={daily_checkin:'每日签到',daily_post:'每日发帖',daily_comment:'每日回帖',daily_rating:'每日策略评分',tmgm_deposit:'TMGM 注册并入金',follow_x:'关注 X 账号',join_telegram:'加入 Telegram 群组'};

export default function PointsCenter({t,setRoute}){
  const [state,setState]=useState(null);
  const [error,setError]=useState('');
  const [busy,setBusy]=useState('');
  const [forms,setForms]=useState({});
  const refresh=useCallback(async()=>{try{const response=await apiFetch('/api/points',{cache:'no-store'});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||'载入失败');setState(data);setError('');}catch(e){setError(e.message);}},[]);
  // Data arrives asynchronously from the authenticated points endpoint.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{refresh();},[refresh]);
  const send=async(key,body)=>{setBusy(key);setError('');try{const response=await apiFetch('/api/points',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||'提交失败');await refresh();}catch(e){setError(e.message);}finally{setBusy('');}};
  const update=(id,key,value)=>setForms(previous=>({...previous,[id]:{...previous[id],[key]:value}}));
  return <div className="nq-readable min-h-[70vh] bg-[#07101a] px-4 py-8 text-slate-100"><div className="mx-auto max-w-6xl space-y-7">
    <div className="rounded-2xl border border-cyan-400/20 bg-gradient-to-r from-[#0a2134] to-[#061827] p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-sm font-semibold text-cyan-300">Nexus Quant Points</p><h1 className="mt-2 text-3xl font-black">{t('积分资产与任务','Points & Tasks')}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">{t('EA 统一用积分购买，1 元＝1 积分。完成任务获得奖励积分，或充值积分后兑换策略。','EA purchases use points. CNY 1 equals one point. Earn rewards from tasks or recharge points to redeem strategies.')}</p></div><div className="rounded-xl border border-amber-400/30 bg-amber-400/10 px-6 py-4"><div className="flex items-center gap-2 text-sm text-amber-200"><Coins className="h-5 w-5"/>{t('可用积分','Available points')}</div><strong className="mt-1 block text-3xl">{state?.balance??'—'}</strong></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[[t('充值来源','Paid origin'),state?.funded],[t('任务奖励来源','Reward origin'),state?.bonus]].map(([label,value])=><div key={label} className="rounded-xl border border-white/10 bg-slate-950/40 p-3 text-sm"><span className="text-slate-400">{label}</span><strong className="mt-1 block text-lg text-white">{value??'—'}</strong></div>)}</div></div>
    {error&&<p role="alert" className="rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}
    {state?.tasksEnabled!==false&&<>    <section><div className="mb-4 flex items-end justify-between gap-3"><h2 className="text-xl font-bold">{t('每日任务','Daily tasks')}</h2><button className="text-sm text-cyan-300 hover:underline" onClick={()=>setRoute('forum')}>{t('进入论坛','Open forum')} →</button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{state?.tasks.filter(task=>task.cadence==='daily').map(task=>{const done=state.todayRewards.includes(task.code);return <div key={task.id} className="rounded-xl border border-slate-700 bg-slate-900/70 p-5"><div className="flex items-start justify-between gap-2"><h3 className="font-bold">{labels[task.code]||task.title}</h3><strong className="text-amber-300">+{task.rewardPoints}</strong></div><p className="mt-2 min-h-10 text-sm text-slate-400">{task.description}</p>{task.code==='daily_checkin'?<button disabled={done||!!busy} onClick={()=>send('checkin',{action:'checkin'})} className="mt-4 w-full rounded-lg bg-cyan-600 px-3 py-2 text-sm font-bold disabled:cursor-not-allowed disabled:bg-slate-700">{done?t('今日已完成','Done today'):busy==='checkin'?t('处理中…','Processing…'):t('签到领取','Check in')}</button>:<span className="mt-4 inline-flex items-center gap-1 text-sm text-slate-300">{done?<><CheckCircle2 className="h-4 w-4 text-emerald-400"/>{t('今日已完成','Done today')}</>:t('完成对应操作后自动发放','Automatically awarded after the action')}</span>}</div>;})}</div></section>
    <section><h2 className="mb-4 text-xl font-bold">{t('审核任务','Reviewed tasks')}</h2><div className="grid gap-4 lg:grid-cols-2">{state?.tasks.filter(task=>task.reviewMode==='manual').map(task=>{const claim=state.claims.find(item=>item.taskId===task.id);const form=forms[task.id]||{};const locked=claim&&claim.status!=='rejected';const missingLink=['follow_x','join_telegram'].includes(task.code)&&!task.targetUrl;return <div key={task.id} className="rounded-xl border border-slate-700 bg-slate-900/70 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-lg font-bold">{labels[task.code]||task.title}</h3><strong className="text-amber-300">+{task.rewardPoints} {t('积分','points')}</strong></div><p className="mt-2 text-sm leading-6 text-slate-400">{task.description}</p>{task.targetUrl&&<a className="mt-3 inline-flex items-center gap-1 text-sm text-cyan-300 hover:underline" href={task.targetUrl} target="_blank" rel="noopener noreferrer">{t('打开任务链接','Open task link')}<ArrowUpRight className="h-4 w-4"/></a>}{missingLink&&<p className="mt-3 text-sm text-amber-300">{t('任务链接待管理员配置，暂不能提交。','The task link is not configured yet.')}</p>}{claim&&<p className="mt-3 flex items-center gap-1 text-sm text-slate-300"><Clock3 className="h-4 w-4"/>{claim.status==='pending'?t('等待管理员核验','Awaiting review'):claim.status==='approved'?t('已审核通过','Approved'):t('已驳回，可修正后重新提交','Rejected; you may resubmit')}{claim.reviewerNote?` · ${claim.reviewerNote}`:''}</p>}{!locked&&!missingLink&&<div className="mt-4 space-y-3">{task.code==='tmgm_deposit'?<><input type="email" maxLength={254} value={form.contactEmail||''} onChange={event=>update(task.id,'contactEmail',event.target.value)} placeholder={t('TMGM 注册邮箱','TMGM registered email')} className="w-full rounded-lg border border-slate-600 bg-slate-950 px-3 py-2 text-sm"/><input maxLength={80} value={form.customerId||''} onChange={event=>update(task.id,'customerId',event.target.value)} placeholder={t('TMGM 客户 ID','TMGM customer ID')} className="w-full rounded-lg border border-slate-600 bg-slate-950 px-3 py-2 text-sm"/><p className="text-xs text-slate-400">{t('仅提交账号标识，管理员核实实际入金后发放；不要提交密码。','Submit account identifiers only. An admin verifies the deposit; never submit a password.')}</p></>:<input maxLength={500} value={form.proofText||''} onChange={event=>update(task.id,'proofText',event.target.value)} placeholder={task.proofLabel||t('填写可供核验的账号或证明','Account or proof for review')} className="w-full rounded-lg border border-slate-600 bg-slate-950 px-3 py-2 text-sm"/>}<button disabled={!!busy} onClick={()=>send(`claim:${task.id}`,{action:'submit_claim',taskId:task.id,contactEmail:form.contactEmail||'',customerId:form.customerId||'',proofText:form.proofText||''})} className="rounded-lg bg-cyan-600 px-4 py-2 text-sm font-bold disabled:opacity-50">{t('提交审核','Submit for review')}</button></div>}</div>;})}</div></section>
</>}
    {state?.tasksEnabled===false&&<section className="rounded-xl border border-slate-700 p-5"><h2 className="font-bold">{t('积分任务暂未开放','Point tasks are closed')}</h2><p className="mt-2 text-sm text-slate-400">{t('余额与历史积分不受影响；已有提交继续由管理员处理。','Balances and point history remain available. Existing submissions can still be reviewed.')}</p>{state.claims.map(claim=><div className="mt-3 border-t border-slate-700 pt-3 text-sm" key={claim.id}>{labels[claim.code]||claim.taskTitle||t('自定义任务','Custom task')} · {claim.status==='pending'?t('审核中','Under review'):claim.status==='approved'?t('已通过','Approved'):t('已驳回','Rejected')}{claim.reviewerNote&&<p className="mt-1 text-slate-400">{claim.reviewerNote}</p>}</div>)}</section>}
    <section className="grid gap-4 lg:grid-cols-2"><PointHistory transactions={state?.transactions||[]} tasks={state?.tasks||[]} t={t}/><PointRechargePanel state={state} refresh={refresh} t={t}/></section>

  </div></div>;
}
