"use client";
import Image from 'next/image';
import Link from 'next/link';
import {Bell,Box,ClipboardCheck,Coins,Download,FileKey2,Heart,Receipt,Settings,Upload,UserRound} from 'lucide-react';
import {Badge,Button,Panel} from './ui/UiKit';
import ProfileEmptyState from './ProfileEmptyState';

export function PersonalNavigation({tab,setTab,setRoute,user,t,hasPublications=false}) {
  const sections=[['assets',t('我的 EA','My EAs'),Box],['points',t('积分与任务','Points and tasks'),Coins],['orders',t('EA 兑换记录','EA redemptions'),Receipt],['recharges',t('充值记录','Recharge history'),Coins],['inbox',t('通知与私信','Notifications and messages'),Bell],['social',t('收藏','Favorites'),Heart],['licenses',t('运行授权','Runtime licenses'),FileKey2],['security',t('账户设置','Account settings'),Settings]];
  return <aside className="reference-personal-nav"><h2><UserRound size={19}/>{t('个人中心','Personal center')}</h2><nav aria-label={t('个人功能导航','Personal functions')}>{sections.map(([key,label,Icon])=><button key={key} aria-current={tab===key?'page':undefined} onClick={()=>['points','inbox'].includes(key)?setRoute(key):setTab(key)}><Icon size={18}/>{label}</button>)}</nav>{(['developer','admin'].includes(user.role)||hasPublications)&&<div className="reference-developer-nav"><h3>{t('开发者','Developer')}</h3><button aria-current={tab==='strategies'?'page':undefined} onClick={()=>setTab('strategies')}><Upload size={18}/>{t('我发布的 EA','My published EAs')}</button>{['developer','admin'].includes(user.role)&&<button aria-current={tab==='withdrawals'?'page':undefined} onClick={()=>setTab('withdrawals')}><Receipt size={18}/>{t('销售与提现','Sales and withdrawals')}</button>}</div>}</aside>;
}
export function PersonalHeader({user,points,myOrders,t,setRoute,edit}) {
  return <><div className="reference-personal-cover"><div className="reference-personal-avatar">{user.avatar_url?<Image src={user.avatar_url} alt="" width={80} height={80}/>:user.username?.slice(0,1)}</div><div><h1>{user.username}</h1><p>{t('专注黄金交易与量化策略','Gold trading and quantitative strategies')}</p></div><Button onClick={edit} variant="ghost">{t('编辑资料','Edit profile')}</Button></div><div className="reference-personal-stats">{[[Coins,t('积分余额','Point balance'),points?.balance??'—',()=>setRoute('points'),t('查看明细','View history')],[Box,t('已兑换 EA','Redeemed EAs'),myOrders.length,null,t('已完成订单','Completed orders')],[ClipboardCheck,t('待审核任务','Tasks under review'),points?points.claims.filter(claim=>claim.status==='pending').length:'—',()=>setRoute('points'),t('查看任务','View tasks')]].map(([Icon,label,value,action,detail])=><Panel key={label}><span><Icon size={26}/></span><div><p>{label}</p><strong>{value}</strong>{action?<button onClick={action}>{detail} →</button>:<small>{detail}</small>}</div></Panel>)}</div></>;
}
export function PurchasedEAList({orders,licenses,t,handleSecureDownload,setBinding,setRoute}) {
  const byProduct=new Map(licenses.filter(item=>item.type!=='trial').map(item=>[item.productId,item]));
  return <Panel className="reference-personal-list"><header><h2>{t('我的 EA','My EAs')}</h2><button onClick={()=>setRoute('market')}>{t('查看更多 EA','Explore more EAs')} →</button></header>{!orders.length?<ProfileEmptyState name="assets" icon={Download} title={t('尚未兑换 EA','No redeemed EAs')} description={t('完成任务获取积分，然后在 EA 下载页选择程序。','Earn points through tasks, then choose a program on the EA downloads page.')} action={<Button onClick={()=>setRoute('market')}>{t('浏览 EA','Browse EAs')}</Button>}/>:orders.map(order=>{const license=byProduct.get(order.product_id);return <div className="reference-owned-ea" key={order.order_id||order.id}><div className="reference-owned-thumbnail">{order.logo_url?<Image src={order.logo_url} width={92} height={60} alt=""/>:<Box size={28}/>}</div><div className="reference-owned-copy"><strong>{order.title}</strong><Badge variant="success">{t('已兑换','Redeemed')}</Badge><p>{order.currentVersion?.version?`v${order.currentVersion.version}`:t('暂无发布版本','No published version')} · {new Date(order.purchase_date).toLocaleDateString()}</p></div><div className="reference-owned-actions">{order.latestEligibleVersion?<Button variant="primary" size="sm" onClick={()=>handleSecureDownload(order.product_id,order.title,order.latestEligibleVersion.id)}>{t('下载程序','Download program')}</Button>:<span>{t('暂无可下载版本','No eligible version')}</span>}<Link href="/ea-strategies">{t('安装指南','Installation guide')}</Link>{license&&<Button size="sm" variant="ghost" onClick={()=>setBinding(license)}>{t('管理授权','Manage license')}</Button>}</div></div>})}</Panel>;
}
export function PersonalTasks({points,t,setRoute}) {
  const names={tmgm_deposit:t('完成 TMGM 注册与入金','TMGM registration and deposit'),follow_x:t('关注 X 账号','Follow X'),join_telegram:t('加入 Telegram 群组','Join Telegram')};
  const states={pending:[t('审核中','Under review'),'primary'],approved:[t('已通过','Approved'),'success'],rejected:[t('需补充资料','More information needed'),'warning']};
  return <Panel className="reference-personal-list"><header><h2>{t('我的任务','My tasks')}</h2><button onClick={()=>setRoute('points')}>{t('查看全部','View all')} →</button></header>{points?.claims?.length?points.claims.slice(0,3).map(claim=><div className="reference-personal-task" key={claim.id}><ClipboardCheck size={21}/><strong>{names[claim.code]||claim.taskTitle||points.tasks?.find(task=>task.id===claim.taskId)?.title||t('自定义任务','Custom task')}</strong><Badge variant={states[claim.status]?.[1]}>{states[claim.status]?.[0]||claim.status}</Badge><time>{new Date(claim.createdAt).toLocaleDateString()}</time><button onClick={()=>setRoute('points')}>{t('查看详情','Details')} →</button></div>):<p className="reference-task-empty">{points?t('暂无提交记录，去任务中心查看可获得的积分。','No submissions. Explore available rewards in the task center.'):t('任务记录尚未加载，请在任务中心查看。','Task history has not loaded. Open the task center.')}</p>}</Panel>;
}
