import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const file=path.resolve('.tmp-inbox-test.db');
const remove=()=>{for(const suffix of ['','-wal','-shm'])try{fs.rmSync(file+suffix)}catch{}};
remove();process.env.NEXUS_DB_PATH=file;
const {default:db}=await import('../lib/db.js');
const {sendMessage,messageThreads,messageConversation,readConversation,setMessageBlock,notificationState,readNotification}=await import('../lib/inbox.js');
const add=db.prepare("INSERT INTO users(username,email,role,password) VALUES(?,?,'user','hash')");
const alice=Number(add.run('alice','alice@test.invalid').lastInsertRowid);
const bob=Number(add.run('bob','bob@test.invalid').lastInsertRowid);
const carol=Number(add.run('carol','carol@test.invalid').lastInsertRowid);
const first=sendMessage(alice,'bob','hello');
assert.equal(messageThreads(bob)[0].unread,1);
assert.equal(messageConversation(bob,alice).items[0].body,'hello');
assert.equal(messageThreads(carol).length,0);
assert.equal(notificationState(bob).items[0].kind,'message');
assert.throws(()=>readNotification(carol,notificationState(bob).items[0].id),/NOTIFICATION_NOT_FOUND/);
readNotification(bob,notificationState(bob).items[0].id);
assert.equal(notificationState(bob).unread,0);
readConversation(bob,alice);
assert.equal(messageThreads(bob)[0].unread,0);
setMessageBlock(bob,alice,true);
assert.throws(()=>sendMessage(alice,'bob','blocked'),/MESSAGE_BLOCKED/);
setMessageBlock(bob,alice,false);
assert.equal(sendMessage(alice,'bob','again').id>first.id,true);
assert.equal(messageConversation(bob,alice,first.id).items.length,0);
db.close();remove();console.log('Inbox isolation and blocking tests passed');
