import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'nq-license-'));process.env.NODE_ENV='test';process.env.NEXUS_DB_PATH=path.join(root,'data.db');process.env.LICENSE_SIGNING_SECRET='test-signing-secret-0123456789abcdef';process.env.LICENSE_BINDING_SECRET='test-binding-secret-0123456789abcdef';
let db;try{({default:db}=await import('../lib/db.js'));const licensing=await import('../lib/licensing.js');
const owner=Number(db.prepare("INSERT INTO users(username,email,password,role) VALUES('owner','owner@test','x','developer')").run().lastInsertRowid),buyer=Number(db.prepare("INSERT INTO users(username,email,password,role) VALUES('buyer','buyer@test','x','user')").run().lastInsertRowid),admin=Number(db.prepare("INSERT INTO users(username,email,password,role) VALUES('admin','admin@test','x','admin')").run().lastInsertRowid);
const product=Number(db.prepare("INSERT INTO products(title,author,author_user_id,status,price,trial_enabled,trial_days,file_url) VALUES('Trial EA','owner',?,'active',99,1,30,'/private/eas/a.ex5')").run(owner).lastInsertRowid);const upload=Number(db.prepare("INSERT INTO uploads(owner_user_id,url,kind,original_name,size,stored_name,content_sha256,status,attached_product_id) VALUES(?,'/private/eas/a.ex5','ea','a.ex5',100,'a.ex5',?,'attached',?)").run(owner,'a'.repeat(64),product).lastInsertRowid);const version=Number(db.prepare("INSERT INTO product_versions(product_id,version,release_notes,upload_id,file_url,content_sha256,upgrade_policy,status,is_current,submitted_by_user_id,created_at,released_at) VALUES(?,'1.0.0','Initial',?,'/private/eas/a.ex5',?,'all_existing','published',1,?,?,?)").run(product,upload,'a'.repeat(64),owner,Date.now(),Date.now()).lastInsertRowid);
const trial=licensing.startTrial(buyer,product);assert.equal(trial.status,'active');assert.equal(trial.versionId,version);const expiry=trial.expiresAt;assert.equal(licensing.startTrial(buyer,product).replayed,true);assert.equal(licensing.getLicense(trial.id).expiresAt,expiry,'replay must not extend trial');
assert.equal(licensing.findDownloadLicense(buyer,db.prepare('SELECT * FROM product_versions WHERE id=?').get(version)),null,'trial download requires both bindings');
licensing.bindLicense(trial.id,buyer,'trading_account','12345678');licensing.bindLicense(trial.id,buyer,'device','DEVICE-FINGERPRINT-123456');const stored=db.prepare('SELECT binding_hash,display_mask FROM license_bindings WHERE license_id=? ORDER BY id').all(trial.id);assert.equal(JSON.stringify(stored).includes('12345678'),false);assert.equal(JSON.stringify(stored).includes('DEVICE-FINGERPRINT-123456'),false);
const issued=licensing.issueLicenseToken(trial.id,buyer,'12345678','DEVICE-FINGERPRINT-123456');assert.equal(licensing.verifyLicenseToken(issued.token,'12345678','DEVICE-FINGERPRINT-123456').valid,true);assert.throws(()=>licensing.verifyLicenseToken(issued.token,'99999999','DEVICE-FINGERPRINT-123456'),/BINDING_MISMATCH/);
const future=Date.now()+8*86400000;licensing.bindLicense(trial.id,buyer,'device','DEVICE-FINGERPRINT-CHANGED',future);assert.throws(()=>licensing.verifyLicenseToken(issued.token,'12345678','DEVICE-FINGERPRINT-123456',future),/LICENSE_INACTIVE|TOKEN_EXPIRED/);assert.throws(()=>licensing.bindLicense(trial.id,buyer,'device','DEVICE-FINGERPRINT-SECOND',future+1000),/REBIND_COOLDOWN/);licensing.bindLicense(trial.id,buyer,'device','DEVICE-FINGERPRINT-SECOND',future+8*86400000);assert.throws(()=>licensing.bindLicense(trial.id,buyer,'device','DEVICE-FINGERPRINT-THIRD',future+16*86400000),/REBIND_LIMIT/);
const revoked=licensing.revokeLicense(trial.id,'管理员发现授权滥用',admin);assert.equal(revoked.status,'revoked');assert.equal(licensing.revokeLicense(trial.id,'管理员发现授权滥用',admin).replayed,true);
const order=Number(db.prepare("INSERT INTO orders(username,buyer_user_id,product_id,price,status,tx_hash,payment_verified) VALUES('buyer',?,?,0,'completed','FREE-L',1)").run(buyer,product).lastInsertRowid);const permanent=licensing.ensureOrderLicense(order);assert.equal(permanent.type,'free');assert.equal(licensing.ensureOrderLicense(order).id,permanent.id);assert.ok(licensing.findDownloadLicense(buyer,db.prepare('SELECT * FROM product_versions WHERE id=?').get(version)));
const nestedBuyer=Number(db.prepare("INSERT INTO users(username,email,password,role) VALUES('nested','nested@test','x','user')").run().lastInsertRowid);const nestedOrder=Number(db.prepare("INSERT INTO orders(username,buyer_user_id,product_id,price,status,tx_hash,payment_verified) VALUES('nested',?,?,0,'completed','FREE-N',1)").run(nestedBuyer,product).lastInsertRowid);const nested=db.transaction(()=>licensing.ensureOrderLicense(nestedOrder)).immediate();assert.equal(nested.type,'free');
assert.equal(db.prepare('PRAGMA foreign_key_check').all().length,0);console.log(JSON.stringify({success:true,assertions:20}));
}finally{db?.close();fs.rmSync(root,{recursive:true,force:true,maxRetries:10,retryDelay:100});}
