import assert from 'node:assert/strict';import crypto from 'node:crypto';import fs from 'node:fs';import path from 'node:path';import Database from 'better-sqlite3';
const {TEST_BASE_URL:base,NEXUS_DB_PATH:dbPath,NEXUS_STORAGE_ROOT:root,JWT_SECRET:sessionSecret,TRUSTED_PROXY_SHARED_SECRET:proxy}=process.env;assert.ok(base&&dbPath&&root&&sessionSecret&&proxy);for(let i=0;i<30;i++){try{if((await fetch(`${base}/api/products`)).ok)break;}catch{}await new Promise(r=>setTimeout(r,250));}
const db=new Database(dbPath);const user=(name,role)=>Number(db.prepare('INSERT INTO users(username,email,password,role) VALUES(?,?,?,?)').run(name,`${name}@test`,'x',role).lastInsertRowid),owner=user('owner','developer'),tester=user('tester','user'),admin=user('admin','admin');const cookie=id=>{const data=Buffer.from(JSON.stringify({id,sv:1,exp:Date.now()+60000})).toString('base64url');return `nexus_token=${data}.${crypto.createHmac('sha256',sessionSecret).update(data).digest('base64url')}`;};const browserHeaders=id=>({cookie:cookie(id),origin:'https://nexus.test','content-type':'application/json','x-forwarded-for':'203.0.113.100','x-nexus-proxy-secret':proxy});
const product=Number(db.prepare("INSERT INTO products(title,author,author_user_id,status,price,trial_enabled,trial_days,file_url) VALUES('Trial API EA','owner',?,'active',199,1,7,'/private/eas/trial.ex5')").run(owner).lastInsertRowid);fs.mkdirSync(root,{recursive:true});const bytes=Buffer.concat([Buffer.from('EX5\x02','binary'),Buffer.alloc(128,7)]);fs.writeFileSync(path.join(root,'trial.ex5'),bytes);const hash=crypto.createHash('sha256').update(bytes).digest('hex');const upload=Number(db.prepare("INSERT INTO uploads(owner_user_id,url,kind,original_name,size,stored_name,content_sha256,status,attached_product_id) VALUES(?,'/private/eas/trial.ex5','ea','trial.ex5',132,'trial.ex5',?,'attached',?)").run(owner,hash,product).lastInsertRowid);const version=Number(db.prepare("INSERT INTO product_versions(product_id,version,release_notes,upload_id,file_url,content_sha256,upgrade_policy,status,is_current,submitted_by_user_id,created_at,released_at) VALUES(?,'1.0.0','Trial build',?,'/private/eas/trial.ex5',?,'all_existing','published',1,?,?,?)").run(product,upload,hash,owner,Date.now(),Date.now()).lastInsertRowid);
let response=await fetch(`${base}/api/licenses`,{method:'POST',headers:browserHeaders(tester),body:JSON.stringify({action:'start_trial',productId:product})});assert.equal(response.status,201);const first=await response.json();const expiry=first.license.expiresAt;response=await fetch(`${base}/api/licenses`,{method:'POST',headers:browserHeaders(tester),body:JSON.stringify({action:'start_trial',productId:product})});const replay=await response.json();assert.equal(replay.replayed,true);assert.equal(replay.license.expiresAt,expiry);
for(const [bindingType,value] of [['trading_account','12345678'],['device','DEVICE-FINGERPRINT-RUNTIME']]){response=await fetch(`${base}/api/licenses`,{method:'POST',headers:browserHeaders(tester),body:JSON.stringify({action:'bind',licenseId:first.license.id,bindingType,value})});assert.equal(response.status,201);}assert.equal(JSON.stringify(db.prepare('SELECT * FROM license_bindings').all()).includes('DEVICE-FINGERPRINT-RUNTIME'),false);
response=await fetch(`${base}/api/licenses/token`,{method:'POST',headers:browserHeaders(tester),body:JSON.stringify({licenseId:first.license.id,tradingAccount:'12345678',deviceFingerprint:'DEVICE-FINGERPRINT-RUNTIME'})});assert.equal(response.status,200);const token=(await response.json()).token;
response=await fetch(`${base}/api/licenses/verify`,{method:'POST',headers:{'content-type':'application/json','x-forwarded-for':'203.0.113.101','x-nexus-proxy-secret':proxy},body:JSON.stringify({token,tradingAccount:'12345678',deviceFingerprint:'DEVICE-FINGERPRINT-RUNTIME'})});assert.equal(response.status,200);
response=await fetch(`${base}/api/licenses/verify`,{method:'POST',headers:{'content-type':'application/json','x-forwarded-for':'203.0.113.102','x-nexus-proxy-secret':proxy},body:JSON.stringify({token,tradingAccount:'99999999',deviceFingerprint:'DEVICE-FINGERPRINT-RUNTIME'})});assert.equal(response.status,401);
assert.equal((await fetch(`${base}/api/download?productId=${product}&versionId=${version}`,{headers:{cookie:cookie(tester)}})).status,200);
response=await fetch(`${base}/api/licenses`,{method:'PATCH',headers:browserHeaders(admin),body:JSON.stringify({licenseId:first.license.id,reason:'管理员运行时撤销测试'})});assert.equal(response.status,200);assert.equal((await fetch(`${base}/api/download?productId=${product}&versionId=${version}`,{headers:{cookie:cookie(tester)}})).status,403);assert.equal(db.prepare('SELECT COUNT(*) count FROM product_version_downloads').get().count,1);console.log(JSON.stringify({success:true,assertions:13}));db.close();
