import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';

const dbPath=path.resolve('.tmp-points-test.db');
const remove=()=>{for(const suffix of ['','-wal','-shm']){try{fs.rmSync(`${dbPath}${suffix}`);}catch{}}};
remove();process.env.NEXUS_DB_PATH=dbPath;
const {default:db}=await import('../lib/db.js');
const {adminPendingCounts,awardDailyAction,pointState,submitPointClaim,reviewPointClaim,redeemWithPoints,configurePointTask,createCustomPointTask}=await import('../lib/points.js');
const {listUserLicenses}=await import('../lib/licensing.js');
const {applyPointAssetDelta,spendPointAssets,creditPointSale,requestPointWithdrawal,reviewPointWithdrawal,pointAssetAccount}=await import('../lib/point-assets.js');
const {setRechargeExchangeRate,createPointRechargeOrder,quotePointRecharge,settleVerifiedPointRecharge}=await import('../lib/point-recharge.js');
const {productPatchSchema}=await import('../lib/validation.js');
let assertions=0;
const equal=(actual,expected,message)=>{assert.deepEqual(actual,expected,message);assertions++;};
const rejects=(fn,pattern)=>{assert.throws(fn,pattern);assertions++;};
const addUser=db.prepare("INSERT INTO users(username,email,role,password) VALUES(?,?,?,'hash')");
const admin=Number(addUser.run('points-admin','points-admin@example.com','admin').lastInsertRowid);
const author=Number(addUser.run('points-author','points-author@example.com','developer').lastInsertRowid);
const buyer=Number(addUser.run('points-buyer','points-buyer@example.com','user').lastInsertRowid);
const fundedBuyer=Number(addUser.run('funded-buyer','funded-buyer@example.com','user').lastInsertRowid);
setRechargeExchangeRate(725);
equal(quotePointRecharge(10).cnyFen,1000,'ten points quote directly to RMB without FX');
equal(quotePointRecharge(1.23).cnyFen,123,'decimal RMB amounts preserve fen exactly');
rejects(()=>quotePointRecharge(1.001),/RECHARGE_POINTS_INVALID/);
const rechargeOrder=createPointRechargeOrder(fundedBuyer,10,'wechat','points-recharge-test-1');
setRechargeExchangeRate(730);
equal(createPointRechargeOrder(fundedBuyer,10,'wechat','points-recharge-test-1').cnyFen,rechargeOrder.cnyFen,'replayed order retains its original CNY quote');
equal(db.prepare('SELECT cny_fen_per_usd FROM point_recharge_orders WHERE id=?').get(rechargeOrder.id).cny_fen_per_usd,100,'new order permanently stores 100 fen per point');
const paidAt=db.prepare('SELECT created_at FROM point_recharge_orders WHERE id=?').get(rechargeOrder.id).created_at+1000;
rejects(()=>settleVerifiedPointRecharge({orderId:rechargeOrder.id,provider:'wechat',providerTradeNo:'wechat-trade-1',cnyFen:7300,paidAt}),/RECHARGE_PAYMENT_MISMATCH/);
equal(pointAssetAccount(fundedBuyer).fundedUnits,0,'wrong CNY amount never credits points');
equal(settleVerifiedPointRecharge({orderId:rechargeOrder.id,provider:'wechat',providerTradeNo:'wechat-trade-1',cnyFen:1000,paidAt}).replayed,false,'verified provider payment credits once');
equal(pointAssetAccount(fundedBuyer).fundedUnits,1000,'paid recharge creates funded origin points');
equal(settleVerifiedPointRecharge({orderId:rechargeOrder.id,provider:'wechat',providerTradeNo:'wechat-trade-1',cnyFen:1000,paidAt}).replayed,true,'identical callback is idempotent');
equal(pointAssetAccount(fundedBuyer).fundedUnits,1000,'replayed callback cannot credit twice');
rejects(()=>settleVerifiedPointRecharge({orderId:rechargeOrder.id,provider:'wechat',providerTradeNo:'wechat-trade-2',cnyFen:1000,paidAt}),/RECHARGE_PAYMENT_CONFLICT/);
const secondRecharge=createPointRechargeOrder(fundedBuyer,5,'wechat','points-recharge-test-2');
rejects(()=>settleVerifiedPointRecharge({orderId:secondRecharge.id,provider:'wechat',providerTradeNo:'wechat-trade-1',cnyFen:500,paidAt:Date.now()+1000}),/RECHARGE_TRADE_ALREADY_USED/);
const expiredRecharge=createPointRechargeOrder(fundedBuyer,5,'alipay','points-recharge-test-3',Date.now()-20*60_000);
rejects(()=>settleVerifiedPointRecharge({orderId:expiredRecharge.id,provider:'alipay',providerTradeNo:'alipay-trade-1',cnyFen:500,paidAt:Date.now()}),/RECHARGE_ORDER_NOT_PAYABLE/);
const product=Number(db.prepare("INSERT INTO products(title,author,author_user_id,price,status) VALUES('Points EA','points-author',?,99,'active')").run(author).lastInsertRowid);
equal(productPatchSchema.safeParse({id:product,pointsPrice:100}).success,true,'publisher points-only edit accepts an integer price');
equal(productPatchSchema.safeParse({id:product,pointsPrice:null}).success,true,'publisher can disable points redemption');
equal(productPatchSchema.safeParse({id:product,pointsPrice:1.5}).success,false,'fractional points price is rejected');
equal(productPatchSchema.safeParse({id:product,pointsPrice:-1}).success,false,'negative points price is rejected');
db.prepare("INSERT INTO uploads(id,owner_user_id,url,kind,size,stored_name,content_sha256,status,created_at) VALUES(880,?,'private://points-test','ea',10,'test.ex5','hash','attached',?)").run(author,Date.now());
db.prepare("INSERT INTO product_versions(product_id,version,release_notes,upload_id,file_url,content_sha256,upgrade_policy,status,is_current,submitted_by_user_id,created_at) VALUES(?,'1.0.0','test',880,'private://points-test','hash','all_existing','published',1,?,?)").run(product,author,Date.now());
db.prepare('UPDATE products SET points_price=100 WHERE id=?').run(product);
const first=Date.parse('2026-10-06T16:01:00Z');
equal(awardDailyAction(buyer,'daily_checkin',null,first).awarded,5,'check-in awards configured points');
equal(awardDailyAction(buyer,'daily_checkin',null,first+1000).awarded,0,'repeat check-in on Shanghai day gives nothing');
const postTask=db.prepare("SELECT * FROM point_tasks WHERE code='daily_post'").get();
configurePointTask(postTask.id,{title:postTask.title,description:postTask.description,rewardPoints:50,targetUrl:'',proofLabel:'',enabled:true});
equal(awardDailyAction(buyer,'daily_post',11,first).awarded,50,'daily post gets configured reward');
equal(awardDailyAction(buyer,'daily_post',12,first+2000).awarded,0,'second daily post gives nothing');
equal(awardDailyAction(buyer,'daily_post',11,first+86400000).awarded,0,'same source cannot be rewarded again next day');
equal(awardDailyAction(buyer,'daily_post',13,first+86400000).awarded,50,'new post on next Shanghai day is rewarded');
equal(pointState(buyer).balance,105,'balance matches ledger');
rejects(()=>redeemWithPoints({id:buyer,username:'points-buyer'},product,99,first+86400000),/POINT_PRICE_CHANGED/);
const result=redeemWithPoints({id:buyer,username:'points-buyer'},product,100,first+86400000);
equal(result.spent,100,'redemption debits strategy points price');
equal(result.balance,5,'redemption leaves correct balance');
equal(db.prepare('SELECT price,status FROM orders WHERE id=?').get(result.orderId),{price:0,status:'completed'},'points create zero-dollar entitlement order');
equal(db.prepare('SELECT price_units,bonus_spent_units,creator_bonus_units,creator_funded_units FROM point_asset_sales WHERE order_id=?').get(result.orderId),{price_units:10000,bonus_spent_units:10000,creator_bonus_units:8000,creator_funded_units:0},'reward-funded purchase creates only nonwithdrawable creator revenue');
equal(db.prepare('SELECT COUNT(*) n FROM product_licenses WHERE source_order_id=?').get(result.orderId).n,1,'redemption grants download license');
equal(listUserLicenses(buyer)[0].type,'points','asset license identifies point redemption');
equal(pointState(author).withdrawable,0,'reward-funded purchase cannot become creator cash-out');
rejects(()=>redeemWithPoints({id:buyer,username:'points-buyer'},product,100),/ALREADY_OWNED/);
const expensive=Number(db.prepare("INSERT INTO products(title,author,author_user_id,price,status,points_price) VALUES('Expensive EA','points-author',?,199,'active',50)").run(author).lastInsertRowid);
db.prepare("INSERT INTO uploads(id,owner_user_id,url,kind,size,stored_name,content_sha256,status,created_at) VALUES(881,?,'private://points-test-2','ea',10,'test-2.ex5','hash2','attached',?)").run(author,Date.now());
db.prepare("INSERT INTO product_versions(product_id,version,release_notes,upload_id,file_url,content_sha256,upgrade_policy,status,is_current,submitted_by_user_id,created_at) VALUES(?,'1.0.0','test',881,'private://points-test-2','hash2','all_existing','published',1,?,?)").run(expensive,author,Date.now());
rejects(()=>redeemWithPoints({id:buyer,username:'points-buyer'},expensive,50),/INSUFFICIENT_POINTS/);
equal(db.prepare('SELECT COUNT(*) n FROM orders WHERE product_id=? AND buyer_user_id=?').get(expensive,buyer).n,0,'insufficient balance leaves no order');
const tmgm=db.prepare("SELECT id FROM point_tasks WHERE code='tmgm_deposit'").get().id;
rejects(()=>submitPointClaim(buyer,tmgm,{contactEmail:'',customerId:''}),/BROKER_PROOF_REQUIRED/);
const claim=submitPointClaim(buyer,tmgm,{contactEmail:'buyer@example.com',customerId:'TMGM-123'});
rejects(()=>submitPointClaim(buyer,tmgm,{contactEmail:'buyer@example.com',customerId:'TMGM-123'}),/CLAIM_EXISTS/);
equal(reviewPointClaim(admin,claim,true).awarded,100,'admin-approved TMGM task awards once');
rejects(()=>reviewPointClaim(admin,claim,true),/CLAIM_ALREADY_REVIEWED/);
const custom=createCustomPointTask({title:'自定义核验',description:'描述',rewardPoints:7,targetUrl:'',proofLabel:'账号',enabled:true});
const customClaim=submitPointClaim(buyer,custom,{proofText:'proof'});
equal(reviewPointClaim(admin,customClaim,false,'证据不足').awarded,0,'rejection gives no points');
equal(submitPointClaim(buyer,custom,{proofText:'corrected'}),customClaim,'rejected claim can be corrected');
equal(reviewPointClaim(admin,customClaim,true).awarded,7,'corrected custom claim can be approved');
const followX=db.prepare("SELECT id FROM point_tasks WHERE code='follow_x'").get().id;
rejects(()=>submitPointClaim(buyer,followX,{proofText:'@account'}),/TASK_LINK_UNAVAILABLE/);
db.prepare("INSERT INTO settings(key,value) VALUES('socialXUrl','https://x.com/nexusquant') ON CONFLICT(key) DO UPDATE SET value=excluded.value").run();
const xClaim=submitPointClaim(buyer,followX,{proofText:'@account'});
equal(db.prepare('SELECT status FROM point_task_claims WHERE id=?').get(xClaim).status,'pending','X claim waits for human verification');
equal(db.prepare('SELECT SUM(funded_delta+bonus_delta) sum FROM point_asset_transactions WHERE user_id=?').get(buyer).sum/100,pointState(buyer).balance,'asset ledger deltas reconcile with balance');
applyPointAssetDelta(fundedBuyer,{funded:12500},'test:recharge:1','verified_recharge');
db.prepare('UPDATE products SET points_price=50 WHERE id=?').run(expensive);
const fundedSale=redeemWithPoints({id:fundedBuyer,username:'funded-buyer'},expensive,50,first+2*86400000);
equal(db.prepare('SELECT funded_spent_units,creator_funded_units,platform_funded_units FROM point_asset_sales WHERE order_id=?').get(fundedSale.orderId),{funded_spent_units:5000,creator_funded_units:4000,platform_funded_units:1000},'paid-origin sale splits creator and platform 80/20');
equal(pointState(author).withdrawable,40,'only paid-origin sale credits withdrawable developer points');
rejects(()=>requestPointWithdrawal(author,100,'Alipay test account'),/INSUFFICIENT_WITHDRAWABLE_POINTS/);
applyPointAssetDelta(author,{funded:7000,withdrawable:7000},'test:old-wallet','legacy_balance_migration');
const withdrawal=requestPointWithdrawal(author,100,'Alipay test account');
equal({currency:withdrawal.currency,amountCny:withdrawal.amountCny},{currency:'CNY',amountCny:100},'withdrawal settles 100 points as RMB 100');
equal(pointAssetAccount(author).withdrawableUnits,1000,'request holds funded withdrawable points');
rejects(()=>requestPointWithdrawal(author,100,'Alipay test account'),/WITHDRAWAL_PENDING/);
equal(reviewPointWithdrawal(admin,withdrawal.id,false,'test').status,'rejected','rejection refunds held points');
equal(pointAssetAccount(author).withdrawableUnits,11000,'rejection restores withdrawable balance');
const mixedBuyer=Number(addUser.run('mixed-buyer','mixed-buyer@example.com','user').lastInsertRowid);
applyPointAssetDelta(mixedBuyer,{funded:9000,bonus:1000},'test:mixed:opening','test_opening');
const mixedDebit=spendPointAssets(mixedBuyer,10000,'test:mixed:purchase');
equal({funded:mixedDebit.fundedSpent,bonus:mixedDebit.bonusSpent},{funded:9000,bonus:1000},'mixed purchase spends reward origin first');
const mixedShare=creditPointSale(author,999,mixedDebit.fundedSpent,mixedDebit.bonusSpent);
equal({funded:mixedShare.creatorFunded,bonus:mixedShare.creatorBonus,platformFunded:mixedShare.platformFunded,platformBonus:mixedShare.platformBonus},{funded:7200,bonus:800,platformFunded:1800,platformBonus:200},'mixed source sale preserves 80/20 split by origin');
const {publicBrokerReward,pointJourneyState}=await import('../lib/point-journey.js');
const {journeyQuote,ownJourneySummary}=await import('../lib/point-journey.mjs');
equal(ownJourneySummary(null,undefined),null,'anonymous home safely renders before points load');
equal(ownJourneySummary({userId:buyer,data:{balance:10}},admin),null,'switching accounts never displays previous user balance');
const summary=pointJourneyState(buyer);
equal(summary.balance,pointState(buyer).balance,'journey uses actual funded and reward balance');
equal(Object.keys(summary).sort(),['balance','brokerClaimStatus'],'home summary does not expose task proof or personal identifiers');
const rewardBefore=db.prepare("SELECT reward_points,enabled FROM point_tasks WHERE code='tmgm_deposit'").get();
db.prepare("UPDATE point_tasks SET reward_points=240,enabled=1 WHERE code='tmgm_deposit'").run();
equal(publicBrokerReward(),{enabled:true,rewardPoints:240},'public reward reads administrator amount');
db.prepare("UPDATE point_tasks SET enabled=0 WHERE code='tmgm_deposit'").run();
equal(publicBrokerReward().enabled,false,'disabled task cannot advertise a reward');
db.prepare("UPDATE point_tasks SET reward_points=?,enabled=? WHERE code='tmgm_deposit'").run(rewardBefore.reward_points,rewardBefore.enabled);
const choices=[{status:'active',points_price:260},{status:'active',points_price:200},{status:'inactive',points_price:1},{status:'active',points_price:0}];
equal(journeyQuote(choices,20,200,'pending'),{minimum:200,affordable:0,gap:180,afterRewardGap:0},'pending rewards do not count toward current affordability');
equal(journeyQuote(choices,20,200,'approved').afterRewardGap,180,'approved reward cannot be added twice');
equal(journeyQuote(choices,null,100,null).affordable,null,'anonymous or unread balances do not become zero');
equal(journeyQuote([],20,200,null).minimum,null,'empty catalog has no invented price');
const {strategyAcquisition}=await import('../lib/strategy-acquisition.mjs');
const ea={status:'active',author_user_id:author,price:200,points_price:260,currentVersion:{id:1,status:'published'}};
equal(strategyAcquisition(ea).state,'login','priced EA has one login entry for anonymous visitors');
equal(strategyAcquisition(ea,{userId:buyer,balance:null}).state,'loading','unread balance is not a zero balance');
equal(strategyAcquisition(ea,{userId:buyer,balance:200}).gap,60,'detail shows exact point shortfall');
equal(strategyAcquisition(ea,{userId:buyer,balance:200}).state,'insufficient','insufficient points direct to tasks');
equal(strategyAcquisition(ea,{userId:buyer,balance:260}).state,'redeem','adequate balance enables redemption');
equal(strategyAcquisition(ea,{userId:author,balance:260}).state,'author','author gets management instead of self-purchase');
equal(strategyAcquisition(ea,{userId:buyer,owned:true}).state,'owned','owned strategy leads to downloads regardless of unread balance');
equal(strategyAcquisition({...ea,points_price:null},{userId:buyer,balance:260}).state,'unpriced','no point price cannot redeem');
equal(strategyAcquisition({...ea,currentVersion:null},{userId:buyer,balance:260}).state,'no_version','no published version cannot promise a download');
equal(strategyAcquisition({...ea,status:'pending'},{userId:buyer,balance:260}).state,'unavailable','pending strategies cannot redeem');
equal(strategyAcquisition({...ea,price:0,points_price:null},{userId:buyer}).state,'free','free acquisition retains its existing flow');
equal(strategyAcquisition(ea,{userId:buyer,balance:NaN}).balance,null,'invalid balance remains unknown');
const pendingBefore=adminPendingCounts();
for (const [key,table] of [['products','products'],['points','point_task_claims'],['pointWithdrawals','point_asset_withdrawals'],['reports','content_reports']]) {
  const filter=key==='products' ? " AND deleted_at IS NULL" : '';
  equal(pendingBefore[key],db.prepare(`SELECT COUNT(*) count FROM ${table} WHERE status='pending'${filter}`).get().count,`${key} workbench count matches the full pending queue`);
}
const pendingTask=db.prepare("SELECT id FROM point_tasks WHERE code='tmgm_deposit'").get();
const newClaim=submitPointClaim(author,pendingTask.id,{contactEmail:'author@example.com',customerId:'workbench-test'});
equal(adminPendingCounts().points,pendingBefore.points+1,'new manual task appears in workbench');
reviewPointClaim(admin,newClaim,false,'test rejected');
equal(adminPendingCounts().points,pendingBefore.points,'reviewed task leaves the pending queue');
const verified=spawnSync(process.execPath,['scripts/point-asset-maintenance.mjs'],{cwd:process.cwd(),env:process.env,encoding:'utf8'});
equal(verified.status,0,'point asset maintenance verifies the untampered ledger');
db.prepare('UPDATE point_asset_accounts SET bonus_units=bonus_units+1 WHERE user_id=?').run(mixedBuyer);
const tampered=spawnSync(process.execPath,['scripts/point-asset-maintenance.mjs'],{cwd:process.cwd(),env:process.env,encoding:'utf8'});
equal(tampered.status,1,'point asset maintenance detects account tampering');
db.close();remove();
console.log(`Points tests passed: ${assertions} assertions`);
