import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const dbPath=path.resolve('.tmp-points-test.db');
const remove=()=>{for(const suffix of ['','-wal','-shm']){try{fs.rmSync(`${dbPath}${suffix}`);}catch{}}};
remove();process.env.NEXUS_DB_PATH=dbPath;
const {default:db}=await import('../lib/db.js');
const {awardDailyAction,pointState,submitPointClaim,reviewPointClaim,redeemWithPoints,configurePointTask,createCustomPointTask}=await import('../lib/points.js');
const {listUserLicenses}=await import('../lib/licensing.js');
const {productPatchSchema}=await import('../lib/validation.js');
let assertions=0;
const equal=(actual,expected,message)=>{assert.deepEqual(actual,expected,message);assertions++;};
const rejects=(fn,pattern)=>{assert.throws(fn,pattern);assertions++;};
const addUser=db.prepare("INSERT INTO users(username,email,role,password) VALUES(?,?,?,'hash')");
const admin=Number(addUser.run('points-admin','points-admin@example.com','admin').lastInsertRowid);
const author=Number(addUser.run('points-author','points-author@example.com','developer').lastInsertRowid);
const buyer=Number(addUser.run('points-buyer','points-buyer@example.com','user').lastInsertRowid);
const product=Number(db.prepare("INSERT INTO products(title,author,author_user_id,price,status) VALUES('Points EA','points-author',?,99,'active')").run(author).lastInsertRowid);
equal(productPatchSchema.safeParse({id:product,pointsPrice:100}).success,true,'publisher points-only edit accepts an integer price');
equal(productPatchSchema.safeParse({id:product,pointsPrice:null}).success,true,'publisher can disable points redemption');
equal(productPatchSchema.safeParse({id:product,pointsPrice:1.5}).success,false,'fractional points price is rejected');
equal(productPatchSchema.safeParse({id:product,pointsPrice:-1}).success,false,'negative points price is rejected');
db.prepare("INSERT INTO uploads(id,owner_user_id,url,kind,size,stored_name,content_sha256,status,created_at) VALUES(880,?,'private://points-test','ea',10,'test.ex5','hash','attached',?)").run(author,Date.now());
db.prepare("INSERT INTO product_versions(product_id,version,release_notes,upload_id,file_url,content_sha256,upgrade_policy,status,is_current,submitted_by_user_id,created_at) VALUES(?,'1.0.0','test',880,'private://points-test','hash','all_existing','published',1,?,?)").run(product,author,Date.now());
db.prepare('UPDATE products SET points_price=100 WHERE id=?').run(product);
const first=Date.parse('2026-10-06T16:01:00Z');
equal(awardDailyAction(buyer,'daily_checkin',null,first).awarded,5,'check-in awards configured points');
equal(awardDailyAction(buyer,'daily_checkin',null,first+1000).awarded,0,'repeat check-in on Shanghai day gives nothing');
const postTask=db.prepare("SELECT * FROM point_tasks WHERE code='daily_post'").get();
configurePointTask(postTask.id,{title:postTask.title,description:postTask.description,rewardPoints:50,targetUrl:'',proofLabel:'',enabled:true});
equal(awardDailyAction(buyer,'daily_post',11,first).awarded,50,'daily post gets configured reward');
equal(awardDailyAction(buyer,'daily_post',12,first+2000).awarded,0,'second daily post gives nothing');
equal(awardDailyAction(buyer,'daily_post',11,first+86400000).awarded,0,'same source cannot be rewarded again next day');
equal(awardDailyAction(buyer,'daily_post',13,first+86400000).awarded,50,'new post on next Shanghai day is rewarded');
equal(pointState(buyer).balance,105,'balance matches ledger');
rejects(()=>redeemWithPoints({id:buyer,username:'points-buyer'},product,99,first+86400000),/POINT_PRICE_CHANGED/);
const result=redeemWithPoints({id:buyer,username:'points-buyer'},product,100,first+86400000);
equal(result.spent,100,'redemption debits strategy points price');
equal(result.balance,5,'redemption leaves correct balance');
equal(db.prepare('SELECT price,status FROM orders WHERE id=?').get(result.orderId),{price:0,status:'completed'},'points create zero-dollar entitlement order');
equal(db.prepare('SELECT points_spent FROM point_redemptions WHERE order_id=?').get(result.orderId).points_spent,100,'redemption method is recorded separately');
equal(db.prepare('SELECT COUNT(*) n FROM product_licenses WHERE source_order_id=?').get(result.orderId).n,1,'redemption grants download license');
equal(listUserLicenses(buyer)[0].type,'points','asset license identifies point redemption');
rejects(()=>redeemWithPoints({id:buyer,username:'points-buyer'},product,100),/ALREADY_OWNED/);
const expensive=Number(db.prepare("INSERT INTO products(title,author,author_user_id,price,status,points_price) VALUES('Expensive EA','points-author',?,199,'active',50)").run(author).lastInsertRowid);
db.prepare("INSERT INTO uploads(id,owner_user_id,url,kind,size,stored_name,content_sha256,status,created_at) VALUES(881,?,'private://points-test-2','ea',10,'test-2.ex5','hash2','attached',?)").run(author,Date.now());
db.prepare("INSERT INTO product_versions(product_id,version,release_notes,upload_id,file_url,content_sha256,upgrade_policy,status,is_current,submitted_by_user_id,created_at) VALUES(?,'1.0.0','test',881,'private://points-test-2','hash2','all_existing','published',1,?,?)").run(expensive,author,Date.now());
rejects(()=>redeemWithPoints({id:buyer,username:'points-buyer'},expensive,50),/INSUFFICIENT_POINTS/);
equal(db.prepare('SELECT COUNT(*) n FROM orders WHERE product_id=? AND buyer_user_id=?').get(expensive,buyer).n,0,'insufficient balance leaves no order');
const tmgm=db.prepare("SELECT id FROM point_tasks WHERE code='tmgm_deposit'").get().id;
rejects(()=>submitPointClaim(buyer,tmgm,{contactEmail:'',customerId:''}),/BROKER_PROOF_REQUIRED/);
const claim=submitPointClaim(buyer,tmgm,{contactEmail:'buyer@example.com',customerId:'TMGM-123'});
rejects(()=>submitPointClaim(buyer,tmgm,{contactEmail:'buyer@example.com',customerId:'TMGM-123'}),/CLAIM_EXISTS/);
equal(reviewPointClaim(admin,claim,true).awarded,100,'admin-approved TMGM task awards once');
rejects(()=>reviewPointClaim(admin,claim,true),/CLAIM_ALREADY_REVIEWED/);
const custom=createCustomPointTask({title:'自定义核验',description:'描述',rewardPoints:7,targetUrl:'',proofLabel:'账号',enabled:true});
const customClaim=submitPointClaim(buyer,custom,{proofText:'proof'});
equal(reviewPointClaim(admin,customClaim,false,'证据不足').awarded,0,'rejection gives no points');
equal(submitPointClaim(buyer,custom,{proofText:'corrected'}),customClaim,'rejected claim can be corrected');
equal(reviewPointClaim(admin,customClaim,true).awarded,7,'corrected custom claim can be approved');
const followX=db.prepare("SELECT id FROM point_tasks WHERE code='follow_x'").get().id;
rejects(()=>submitPointClaim(buyer,followX,{proofText:'@account'}),/TASK_LINK_UNAVAILABLE/);
db.prepare("INSERT INTO settings(key,value) VALUES('socialXUrl','https://x.com/nexusquant') ON CONFLICT(key) DO UPDATE SET value=excluded.value").run();
const xClaim=submitPointClaim(buyer,followX,{proofText:'@account'});
equal(db.prepare('SELECT status FROM point_task_claims WHERE id=?').get(xClaim).status,'pending','X claim waits for human verification');
equal(db.prepare('SELECT SUM(delta) sum FROM point_transactions WHERE user_id=?').get(buyer).sum,pointState(buyer).balance,'ledger deltas reconcile with balance');
db.close();remove();
console.log(`Points tests passed: ${assertions} assertions`);
