import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
process.env.NEXUS_DB_PATH=path.resolve(`.tmp-refunds-${crypto.randomUUID()}.db`);process.env.NEXUS_AUTO_MIGRATE='1';
const app=crypto.generateKeyPairSync('rsa',{modulusLength:2048}),platform=crypto.generateKeyPairSync('rsa',{modulusLength:2048});
process.env.ALIPAY_APP_PRIVATE_KEY=app.privateKey.export({type:'pkcs8',format:'pem'});process.env.ALIPAY_PUBLIC_KEY=platform.publicKey.export({type:'spki',format:'pem'});
const {default:db}=await import('../lib/db.js');
const {createPointRechargeOrder,settleVerifiedPointRecharge}=await import('../lib/point-recharge.js');
const {applyPointAssetDelta,pointAssetAccount,spendPointAssets}=await import('../lib/point-assets.js');
const {refundableUnits,requestRechargeRefund,rejectRechargeRefund,checkRechargeRefund,listRechargeRefunds,runRechargeRefundChecks}=await import('../lib/recharge-refunds.js');
const save=db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value');
for(const [k,v] of Object.entries({alipaySetupEnabled:'true',alipayAppId:'2026000000000000',alipaySellerId:'2088000000000000',alipayNotifyUrl:'https://nqstrategy.com/api/payments/webhooks/alipay',alipayGateway:'https://openapi.alipay.com/gateway.do'}))save.run(k,v);
const user=name=>Number(db.prepare('INSERT INTO users(username,email,role,password) VALUES(?,?,?,?)').run(name,`${name}@example.com`,name==='admin'?'admin':'user','hash').lastInsertRowid);
const buyer=user('buyer'),other=user('other'),admin={id:user('admin'),role:'admin'},now=Date.now();
const order=(uid,points)=>{const created=createPointRechargeOrder(uid,points,'alipay',crypto.randomUUID(),now);settleVerifiedPointRecharge({orderId:created.id,provider:'alipay',providerTradeNo:`2026101100000${created.id}`,cnyFen:points*100,paidAt:now+1000});return db.prepare('SELECT * FROM point_recharge_orders WHERE id=?').get(created.id);};
const first=order(buyer,10);
applyPointAssetDelta(buyer,{bonus:1000},'reward:1','daily_checkin');
spendPointAssets(buyer,1300,'purchase:1');
assert.equal(refundableUnits(first),700,'rewards spent first; original recharge consumption is tracked');
const later=order(buyer,10);assert.equal(refundableUnits(first),700,'later top-up cannot refill spent original recharge');
const data={orderId:first.id,units:500,reason:'未使用部分退款',requestKey:crypto.randomUUID()};
assert.throws(()=>requestRechargeRefund(other,data),/REFUND_AMOUNT_UNAVAILABLE/);
assert.throws(()=>requestRechargeRefund(buyer,{...data,units:800}),/REFUND_AMOUNT_UNAVAILABLE/);
const refund=requestRechargeRefund(buyer,data);assert.equal(refundableUnits(first),200);assert.equal(pointAssetAccount(buyer).fundedUnits,1200);
assert.equal(requestRechargeRefund(buyer,data).id,refund.id);assert.equal(pointAssetAccount(buyer).fundedUnits,1200,'request replay holds only once');
assert.throws(()=>requestRechargeRefund(buyer,{...data,requestKey:crypto.randomUUID()}),/REFUND_ALREADY_OPEN/);
assert.throws(()=>requestRechargeRefund(buyer,{...data,units:100}),/REFUND_KEY_CONFLICT/);
assert.equal(listRechargeRefunds({id:other,role:'user'}).items.length,0);
assert.throws(()=>listRechargeRefunds({id:buyer,role:'user'},{admin:true}),/REFUND_FORBIDDEN/);
assert.ok(!('request_key' in listRechargeRefunds({id:buyer}).items[0]));
assert.throws(()=>rejectRechargeRefund({id:buyer,role:'user'},refund.id,'拒绝'),/REFUND_FORBIDDEN/);
rejectRechargeRefund(admin,refund.id,'申请撤回');rejectRechargeRefund(admin,refund.id,'申请撤回');assert.equal(refundableUnits(first),700);assert.equal(pointAssetAccount(buyer).fundedUnits,1700);
const second=requestRechargeRefund(buyer,{...data,requestKey:crypto.randomUUID()});
const signed=(method,value)=>new Response(JSON.stringify({[method.replaceAll('.','_')+'_response']:value,sign:crypto.sign('RSA-SHA256',Buffer.from(JSON.stringify(value)),platform.privateKey).toString('base64')}));
const refundReply=(method,status='REFUND_SUCCESS',amount='5.00')=>signed(method,{code:'10000',out_trade_no:`NQPR${first.id}`,trade_no:first.provider_trade_no,out_request_no:`NQRF${second.id}`,refund_amount:amount,refund_fee:amount,refund_status:status,fund_change:'Y'});
await assert.rejects(()=>checkRechargeRefund(second.id,{admin:{role:'user'},submit:true}),/REFUND_FORBIDDEN/);
await assert.rejects(()=>checkRechargeRefund(second.id),/REFUND_NOT_APPROVED/);
let sent=0;
assert.equal((await checkRechargeRefund(second.id,{admin,submit:true,fetchImpl:async()=>{sent++;throw Error('network private details');}})).state,'unknown');
assert.throws(()=>rejectRechargeRefund(admin,second.id,'异常驳回'),/REFUND_CANNOT_REJECT/);
assert.equal(pointAssetAccount(buyer).fundedUnits,1200,'ambiguous result stays held');
assert.equal(listRechargeRefunds(admin,{admin:true}).items.find(x=>x.id===second.id).error_code,'REFUND_PROVIDER_UNAVAILABLE');
const success=await checkRechargeRefund(second.id,{admin,submit:true,fetchImpl:async(url,options)=>{const method=new URLSearchParams(options.body).get('method');assert.equal(method,'alipay.trade.fastpay.refund.query','recover by querying before retry');return refundReply(method);}});
assert.equal(success.state,'paid');assert.equal(sent,1);assert.equal((await checkRechargeRefund(second.id,{admin,submit:true,fetchImpl:()=>{throw Error('must not resend');}})).state,'paid');assert.equal(pointAssetAccount(buyer).fundedUnits,1200);
assert.equal(refundableUnits(first),200);
const third=requestRechargeRefund(buyer,{...data,units:100,requestKey:crypto.randomUUID()});
let release;
const blocked=checkRechargeRefund(third.id,{admin,submit:true,fetchImpl:()=>new Promise(resolve=>{release=()=>resolve(signed('alipay.trade.refund',{code:'10000',out_trade_no:`NQPR${first.id}`,trade_no:first.provider_trade_no,refund_fee:'1.00',fund_change:'N'}));})});
assert.equal((await checkRechargeRefund(third.id,{admin,submit:true})).state,'busy');release();assert.equal((await blocked).state,'unknown','fund_change=N is not success');
assert.equal((await checkRechargeRefund(third.id,{fetchImpl:async()=>signed('alipay.trade.fastpay.refund.query',{code:'10000',out_trade_no:`NQPR${first.id}`,trade_no:first.provider_trade_no,out_request_no:`NQRF${third.id}`,refund_amount:'9.00',refund_status:'REFUND_SUCCESS'})})).state,'unknown','wrong refund amount cannot finalize');
assert.equal(pointAssetAccount(buyer).fundedUnits,1100);
assert.equal((await checkRechargeRefund(third.id,{fetchImpl:async()=>new Response('{"alipay_trade_fastpay_refund_query_response":{"code":"10000"},"sign":"invalid"}')})).state,'unknown','signature rejected');
const count=await runRechargeRefundChecks({now:Date.now()+700000,fetchImpl:async(url,options)=>{assert.equal(new URLSearchParams(options.body).get('method'),'alipay.trade.fastpay.refund.query','worker never submits refunds');return signed('alipay.trade.fastpay.refund.query',{code:'40004',sub_code:'ACQ.REFUND_NOT_EXIST'});}});
assert.equal(count.processed,1);
spendPointAssets(buyer,1000,'purchase:2');assert.equal(refundableUnits(later),100,'FIFO uses the remaining oldest recharge first');
applyPointAssetDelta(other,{funded:1000,withdrawable:1000},'creator:1','strategy_sale');assert.equal(refundableUnits({id:999,user_id:other,status:'paid',provider:'alipay',points_units:1000,cny_fen:1000,cny_fen_per_usd:100}),0,'developer proceeds are never refundable recharge');
assert.equal(refundableUnits({...first,cny_fen:6690}),0,'legacy exchange-rate orders excluded');
const verification=JSON.parse(execFileSync(process.execPath,['scripts/point-asset-maintenance.mjs'],{env:process.env,encoding:'utf8'}));assert.equal(verification.valid,true,JSON.stringify(verification.issues));
db.close();console.log('Recharge refunds passed: owner isolation, FIFO origin, hold/release idempotency, unknown outcomes, signed confirmation, concurrent leases, query-only recovery and ledger integrity');
