$env:NODE_ENV = 'production'
$env:PORT = '3147'
$env:NEXUS_DB_PATH = '.tmp-upload-security-runtime-p2b/test.db'
$env:NEXUS_PUBLIC_UPLOAD_ROOT = '.tmp-upload-security-runtime-p2b/public'
$env:NEXUS_STORAGE_ROOT = '.tmp-upload-security-runtime-p2b/private'
$env:UPLOAD_SCAN_URL = 'http://127.0.0.1:3151/scan'
$env:JWT_SECRET = 'upload-test-jwt-secret-0123456789abcdef'
$env:VERIFICATION_CODE_SECRET = 'upload-test-code-secret-0123456789abcdef'
$env:AUDIT_HASH_SECRET = 'upload-test-hash-secret-0123456789abcdef'
$env:AUDIT_INTEGRITY_SECRET = (Get-Content -LiteralPath 'storage/secrets/audit-integrity.key' -Raw).Trim()
$env:LEDGER_INTEGRITY_SECRET = (Get-Content -LiteralPath 'storage/secrets/ledger-integrity.key' -Raw).Trim()
$env:AUDIT_RETENTION_DAYS = '180'
$env:AUDIT_ARCHIVE_DIR = '.tmp-upload-security-runtime-p2b/archives'
$env:TRUSTED_PROXY_MODE = 'forwarded'
$env:TRUSTED_PROXY_SHARED_SECRET = 'upload-test-proxy-secret-0123456789abcdef'
$env:RATE_LIMIT_BACKEND = 'sqlite'
$env:DEPLOYMENT_TOPOLOGY = 'single-instance'
$env:APP_ORIGINS = 'https://nexus.test'
npm run start
