$env:NODE_ENV='production'
$env:PORT='3170'
$env:NEXUS_DB_PATH='.tmp-version-runtime/data.db'
$env:NEXUS_STORAGE_ROOT='.tmp-version-runtime/private'
$env:NEXUS_PUBLIC_UPLOAD_ROOT='.tmp-version-runtime/public'
$env:NEXUS_EVIDENCE_ROOT='.tmp-version-runtime/evidence'
$env:NEXUS_REPORT_ROOT='.tmp-version-runtime/report'
$env:JWT_SECRET='version-jwt-secret-0123456789abcdef'
$env:AUDIT_INTEGRITY_SECRET='version-audit-secret-0123456789abcdef'
$env:AUDIT_RETENTION_DAYS='180'
$env:LEDGER_INTEGRITY_SECRET='version-ledger-secret-0123456789abcdef'
$env:TRUSTED_PROXY_MODE='forwarded'
$env:TRUSTED_PROXY_SHARED_SECRET='version-proxy-secret-0123456789abcdef'
$env:RATE_LIMIT_BACKEND='sqlite'
$env:DEPLOYMENT_TOPOLOGY='single-instance'
$env:APP_ORIGINS='https://nexus.test'
npm run start
