import crypto from 'node:crypto';
import db from './db.js';
import { validateLicenseConfig } from './license-config.mjs';
import { findEligibleOrder } from './product-versions.js';

const TRIAL_MAX_DAYS=30;
const REBIND_COOLDOWN_MS=7*24*60*60*1000;
const MAX_REBINDS=2;
const TOKEN_TTL_MS=15*60*1000;
let devSecrets;
function secrets(){const configured=validateLicenseConfig(process.env);if(configured.signingSecret&&configured.bindingSecret)return configured;if(!devSecrets)devSecrets={signingSecret:crypto.randomBytes(48).toString('base64url'),bindingSecret:crypto.randomBytes(48).toString('base64url')};return devSecrets;}
const encode=value=>Buffer.from(JSON.stringify(value)).toString('base64url');
const secureEqual=(a,b)=>{const left=crypto.createHash('sha256').update(String(a)).digest(),right=crypto.createHash('sha256').update(String(b)).digest();return crypto.timingSafeEqual(left,right);};
function hashBinding(type,value){return crypto.createHmac('sha256',secrets().bindingSecret).update(`${type}:${String(value).trim().toLowerCase()}`).digest('hex');}
function mask(type,value,hash){const text=String(value).trim();return type==='trading_account'?`${'*'.repeat(Math.max(4,Math.min(8,text.length-4)))}${text.slice(-4)}`:`device-${hash.slice(0,10)}`;}
function effective(row,now=Date.now()){return row.status==='active'&&(!row.expires_at||row.expires_at>now);}
function dto(row,{includePrivate=false}={}){if(!row)return null;const bindings=db.prepare("SELECT binding_type,display_mask,bound_at FROM license_bindings WHERE license_id=? AND status='active'").all(row.id);const product=db.prepare('SELECT title FROM products WHERE id=?').get(row.product_id);const version=row.version_id?db.prepare('SELECT version FROM product_versions WHERE id=?').get(row.version_id):null;return {id:row.id,userId:row.user_id,productId:row.product_id,productTitle:product?.title||null,versionId:row.version_id,version:version?.version||null,type:row.license_type,status:effective(row)?'active':row.status==='revoked'?'revoked':'expired',startsAt:row.starts_at,expiresAt:row.expires_at,bindings:bindings.map(item=>({type:item.binding_type,mask:item.display_mask,boundAt:item.bound_at})),...(includePrivate?{sourceOrderId:row.source_order_id,tokenVersion:row.token_version,revokedAt:row.revoked_at,revocationReason:row.revocation_reason}: {})};}

export function listUserLicenses(userId,{admin=false}={}){const rows=admin?db.prepare('SELECT * FROM product_licenses ORDER BY id DESC').all():db.prepare('SELECT * FROM product_licenses WHERE user_id=? ORDER BY id DESC').all(userId);return rows.map(row=>dto(row,{includePrivate:admin}));}
export function getLicense(id,options){return dto(db.prepare('SELECT * FROM product_licenses WHERE id=?').get(id),options);}

export function ensureOrderLicense(orderId){return db.transaction(()=>{const order=db.prepare("SELECT * FROM orders WHERE id=? AND buyer_user_id IS NOT NULL AND status='completed' AND (price=0 OR payment_verified=1)").get(orderId);if(!order)throw new Error('ORDER_NOT_LICENSED');const existing=db.prepare('SELECT * FROM product_licenses WHERE source_order_id=?').get(order.id);if(existing)return dto(existing);const now=Date.now();const result=db.prepare(`INSERT INTO product_licenses(user_id,product_id,source_order_id,license_type,status,starts_at,created_at)
  VALUES(?,?,?,?,'active',?,?)`).run(order.buyer_user_id,order.product_id,order.id,Number(order.price)===0?'free':'purchase',now,now);return getLicense(result.lastInsertRowid);}).immediate();}

export function startTrial(userId,productId){return db.transaction(()=>{const product=db.prepare('SELECT id,status,author_user_id,trial_enabled,trial_days FROM products WHERE id=?').get(productId);if(!product||product.status!=='active')throw new Error('PRODUCT_UNAVAILABLE');if(product.author_user_id===userId)throw new Error('SELF_TRIAL');if(!product.trial_enabled)throw new Error('TRIAL_DISABLED');const current=db.prepare("SELECT id FROM product_versions WHERE product_id=? AND status='published' AND is_current=1").get(productId);if(!current)throw new Error('VERSION_UNAVAILABLE');const existing=db.prepare("SELECT * FROM product_licenses WHERE user_id=? AND product_id=? AND license_type='trial'").get(userId,productId);if(existing)return {...dto(existing),replayed:true};const permanent=db.prepare("SELECT id FROM product_licenses WHERE user_id=? AND product_id=? AND license_type IN ('purchase','free') AND status='active'").get(userId,productId);if(permanent)throw new Error('ALREADY_OWNED');const now=Date.now(),days=Math.min(TRIAL_MAX_DAYS,Math.max(1,Number(product.trial_days)||7));const result=db.prepare(`INSERT INTO product_licenses(user_id,product_id,version_id,license_type,status,starts_at,expires_at,created_at)
 VALUES(?,?,?,'trial','active',?,?,?)`).run(userId,productId,current.id,now,now+days*86400000,now);return getLicense(result.lastInsertRowid);}).immediate();}

export function bindLicense(licenseId,userId,type,value,now=Date.now()){return db.transaction(()=>{const license=db.prepare('SELECT * FROM product_licenses WHERE id=?').get(licenseId);if(!license)throw new Error('LICENSE_NOT_FOUND');if(license.user_id!==userId)throw new Error('FORBIDDEN');if(!effective(license,now))throw new Error('LICENSE_INACTIVE');const digest=hashBinding(type,value);const current=db.prepare("SELECT * FROM license_bindings WHERE license_id=? AND binding_type=? AND status='active'").get(licenseId,type);if(current?.binding_hash===digest)return {...dto(license),replayed:true};if(current){const changes=db.prepare('SELECT COUNT(*) count,MAX(created_at) last_at FROM license_binding_events WHERE license_id=? AND binding_type=? AND previous_binding_id IS NOT NULL').get(licenseId,type);if(changes.count>=MAX_REBINDS)throw new Error('REBIND_LIMIT');if(changes.last_at&&now-changes.last_at<REBIND_COOLDOWN_MS)throw new Error('REBIND_COOLDOWN');db.prepare("UPDATE license_bindings SET status='replaced',replaced_at=? WHERE id=? AND status='active'").run(now,current.id);}
  const inserted=db.prepare("INSERT INTO license_bindings(license_id,binding_type,binding_hash,display_mask,status,bound_at) VALUES(?,?,?,?,'active',?)").run(licenseId,type,digest,mask(type,value,digest),now);db.prepare('INSERT INTO license_binding_events(license_id,binding_type,previous_binding_id,new_binding_id,actor_user_id,created_at) VALUES(?,?,?,?,?,?)').run(licenseId,type,current?.id||null,inserted.lastInsertRowid,userId,now);db.prepare('UPDATE product_licenses SET token_version=token_version+1 WHERE id=?').run(licenseId);return getLicense(licenseId);}).immediate();}

function requireBindings(licenseId,account,device){for(const [type,value] of [['trading_account',account],['device',device]]){const binding=db.prepare("SELECT binding_hash FROM license_bindings WHERE license_id=? AND binding_type=? AND status='active'").get(licenseId,type);if(!binding)throw new Error('BINDINGS_REQUIRED');if(!secureEqual(binding.binding_hash,hashBinding(type,value)))throw new Error('BINDING_MISMATCH');}}
export function issueLicenseToken(licenseId,userId,account,device,now=Date.now()){const license=db.prepare('SELECT * FROM product_licenses WHERE id=?').get(licenseId);if(!license)throw new Error('LICENSE_NOT_FOUND');if(license.user_id!==userId)throw new Error('FORBIDDEN');if(!effective(license,now))throw new Error('LICENSE_INACTIVE');requireBindings(licenseId,account,device);const payload={lid:license.id,uid:userId,pid:license.product_id,vid:license.version_id||null,lv:license.token_version,iat:now,exp:Math.min(now+TOKEN_TTL_MS,license.expires_at||Number.MAX_SAFE_INTEGER),jti:crypto.randomUUID()};const data=encode(payload);const signature=crypto.createHmac('sha256',secrets().signingSecret).update(data).digest('base64url');return {token:`${data}.${signature}`,expiresAt:payload.exp};}
export function verifyLicenseToken(token,account,device,now=Date.now()){const [data,signature,...extra]=String(token||'').split('.');if(!data||!signature||extra.length)throw new Error('TOKEN_INVALID');const expected=crypto.createHmac('sha256',secrets().signingSecret).update(data).digest('base64url');if(!secureEqual(expected,signature))throw new Error('TOKEN_INVALID');let payload;try{payload=JSON.parse(Buffer.from(data,'base64url').toString('utf8'));}catch{throw new Error('TOKEN_INVALID');}if(!Number.isInteger(payload.lid)||!Number.isInteger(payload.uid)||!Number.isFinite(payload.exp)||payload.exp<=now)throw new Error('TOKEN_EXPIRED');const license=db.prepare('SELECT * FROM product_licenses WHERE id=?').get(payload.lid);if(!license||license.user_id!==payload.uid||license.product_id!==payload.pid||license.token_version!==payload.lv||!effective(license,now))throw new Error('LICENSE_INACTIVE');requireBindings(license.id,account,device);return {valid:true,license:dto(license),productId:license.product_id,versionId:license.version_id,expiresAt:payload.exp};}

export function findDownloadLicense(userId,version){const rows=db.prepare("SELECT * FROM product_licenses WHERE user_id=? AND product_id=? AND status='active' AND starts_at<=? AND (expires_at IS NULL OR expires_at>?) ORDER BY CASE license_type WHEN 'purchase' THEN 1 WHEN 'free' THEN 2 ELSE 3 END,id").all(userId,version.product_id,Date.now(),Date.now());for(const row of rows){if(row.license_type==='trial'){const bindingCount=db.prepare("SELECT COUNT(DISTINCT binding_type) count FROM license_bindings WHERE license_id=? AND status='active' AND binding_type IN ('trading_account','device')").get(row.id).count;if(row.version_id===version.id&&bindingCount===2)return {license:row,order:null};continue;}const order=findEligibleOrder(userId,version);if(order&&order.id===row.source_order_id)return {license:row,order};}return null;}
export function revokeLicense(licenseId,reason,adminId){const now=Date.now();const result=db.prepare("UPDATE product_licenses SET status='revoked',revoked_at=?,revoked_by_user_id=?,revocation_reason=?,token_version=token_version+1 WHERE id=? AND status='active'").run(now,adminId,reason,licenseId);if(result.changes===0){const existing=db.prepare('SELECT * FROM product_licenses WHERE id=?').get(licenseId);if(!existing)throw new Error('LICENSE_NOT_FOUND');if(existing.status==='revoked')return {...dto(existing,{includePrivate:true}),replayed:true};throw new Error('LICENSE_INACTIVE');}return getLicense(licenseId,{includePrivate:true});}
