'use client';
import {useCallback,useEffect,useState} from 'react';
import {apiFetch} from '@/lib/api-client';

const labels={verified_recharge:'充值到账',strategy_purchase:'兑换 EA',strategy_sale:'开发者销售分成',withdrawal_hold:'提现冻结',withdrawal_refund:'提现退回',legacy_balance_migration:'旧余额转入',daily_checkin:'签到奖励',daily_post:'发帖奖励',daily_comment:'回复奖励',daily_rating:'评分奖励',tmgm_deposit:'TMGM 任务奖励',follow_x:'X 关注奖励',join_telegram:'Telegram 奖励'};
const statuses={pending:'待处理',paid:'已支付',expired:'已过期',failed:'失败',completed:'已打款',rejected:'已驳回'};
const units=value=>(Number(value||0)/100).toFixed(2);
export default function FinanceAdmin(){
  const [view,setView]=useState('recharges'),[page,setPage]=useState(1),[userId,setUserId]=useState(''),[filter,setFilter]=useState('');
  const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const result=await (await apiFetch(`/api/points/finance?${new URLSearchParams({view,page:String(page),...(filter?{userId:filter}:{})})}`,{cache:'no-store'})).json();if(!result.success)throw Error(result.message||'流水读取失败');setData(result);}catch(e){setError(e.message);}finally{setLoading(false);}},[view,page,filter]);
  // Read only after mounting or changing pagination/filter.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load();},[load]);
  const summary=data?.summary;
  return <section className="space-y-5 text-sm"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['已核验充值（元）',summary?.rechargeCny],['已完成提现（元）',summary?.withdrawalCny],['EA 兑换总额（积分）',summary?.salesPoints],['平台充值来源分成（积分）',summary?.platformFundedPoints]].map(([title,value])=><div className="rounded-xl border border-slate-700 bg-slate-900/50 p-4" key={title}><p className="text-slate-400">{title}</p><strong className="mt-2 block text-2xl">{value===undefined?'—':value.toFixed(2)}</strong></div>)}</div><p className="text-slate-400">人民币充值只统计已核验到账的订单，待支付订单不计收入。奖励积分与现金收款分别记录；历史美元订单请查看“历史订单与支付”。</p>
    <div className="flex flex-wrap gap-2">{[['recharges','人民币充值订单'],['points','积分账户流水'],['sales','EA 兑换与分成'],['withdrawals','提现流水']].map(([key,label])=><button key={key} onClick={()=>{setView(key);setPage(1);setData(null);}} aria-pressed={view===key} className={`rounded-lg border px-4 py-2 ${view===key?'border-teal-500 bg-teal-600 text-white':'border-slate-700'}`}>{label}</button>)}</div><form onSubmit={e=>{e.preventDefault();setFilter(userId);setPage(1);setData(null);}} className="flex flex-wrap gap-2"><input aria-label="按用户 ID 筛选" type="number" min="1" value={userId} onChange={e=>setUserId(e.target.value)} placeholder="用户 ID（留空查看全部）" className="rounded-lg border border-slate-700 bg-slate-950 p-2"/><button className="rounded-lg border border-slate-700 px-4">筛选</button><button type="button" onClick={load} disabled={loading} className="rounded-lg border border-slate-700 px-4">刷新</button></form>{error&&<p role="alert">{error}</p>}
    <div className="overflow-x-auto rounded-xl border border-slate-700"><table className="w-full min-w-[850px] text-left"><thead><tr className="bg-slate-800/50"><th className="p-3">单号 / 用户</th><th className="p-3">类型 / 状态</th><th className="p-3">金额 / 变动</th><th className="p-3">来源 / 余额 / 凭证</th><th className="p-3">时间</th></tr></thead><tbody>{data?.view===view&&data.items.map(item=><tr key={item.id} className="border-t border-slate-700"><td className="p-3">#{item.id}<br/>{item.username||'已注销用户'} · ID {item.user_id}</td><td className="p-3">{view==='points'?labels[item.reason]||'自定义任务奖励':view==='recharges'?`${item.provider==='alipay'?'支付宝':'微信'} · ${statuses[item.status]||item.status}`:view==='sales'?`EA #${item.product_id}`:statuses[item.status]}</td><td className="p-3">{view==='recharges'?`¥${units(item.cny_fen)} / ${units(item.points_units)} 积分`:view==='points'?`${units(item.funded_delta+item.bonus_delta)} 积分`:view==='sales'?`${units(item.price_units)} 积分`:`¥${units(item.units)}`}</td><td className="max-w-md break-all p-3">{view==='recharges'?item.provider_trade_no||'尚无支付流水号':view==='points'?`充值来源变动 ${units(item.funded_delta)} · 奖励变动 ${units(item.bonus_delta)} · 余额 ${units(item.funded_after+item.bonus_after)} · 可提现 ${units(item.withdrawable_after)}`:view==='sales'?`充值来源 ${units(item.funded_spent_units)} · 奖励来源 ${units(item.bonus_spent_units)} · 开发者 ID ${item.developer_user_id} 可提现分成 ${units(item.creator_funded_units)}`:item.reviewer_note||'待审核或未打款'}</td><td className="p-3">{new Date(item.created_at).toLocaleString('zh-CN')}</td></tr>)}{(!data||!data.items.length)&&<tr><td colSpan={5} className="p-8 text-center">{loading?'正在读取流水…':error?'请重试读取':'暂无记录'}</td></tr>}</tbody></table></div><div className="flex items-center justify-end gap-3"><span>共 {data?.pagination.total??0} 条 · 每页 50 条</span><button disabled={loading||page<=1} onClick={()=>setPage(page-1)} className="rounded border p-2 disabled:opacity-40">上一页</button><span>{page} / {data?.pagination.totalPages||1}</span><button disabled={loading||!data||page>=data.pagination.totalPages} onClick={()=>setPage(page+1)} className="rounded border p-2 disabled:opacity-40">下一页</button></div></section>;
}
