"use client";
import { useState } from 'react';
import { applySitePreset, HOME_MODULES, HOME_MODULE_LABELS, SITE_PRESETS } from '@/lib/home-config.mjs';
import EditorialHome from '@/app/components/EditorialHome';

const control='mt-2 w-full rounded-lg border border-slate-600 bg-transparent px-3 py-2 text-sm';
export default function HomeConfiguration({config,onChange,products=[],settings={}}) {
  const [selected,setSelected]=useState(null),[preview,setPreview]=useState(false);
  const home=config.home;
  const change=(key,value)=>onChange({...config,home:{...home,[key]:value}});
  const move=(index,direction)=>{const modules=[...home.modules];[modules[index],modules[index+direction]]=[modules[index+direction],modules[index]];change('modules',modules);};
  const proposal=selected?applySitePreset(config,selected):null;
  return <div className="space-y-6">
    <div><h3 className="font-bold">站点展示预设</h3><p className="mt-2 text-sm leading-6 text-slate-400">当前预设：{SITE_PRESETS[config.preset]?.label||'自定义'}。预设只调整首页和系统导航；可逐项编辑。主题、论坛状态、品牌资料、页面、商品、价格及积分规则单独保留。</p></div>
    <div className="grid grid-cols-3 gap-4">{Object.entries(SITE_PRESETS).map(([key,value])=><button key={key} onClick={()=>setSelected(key)} className="rounded-xl border border-slate-600 p-4 text-left hover:border-teal-500"><strong>{value.label}</strong><p className="mt-3 text-sm leading-6 text-slate-400">{value.description}</p><span className="mt-3 block text-sm text-teal-500">查看变更 →</span></button>)}</div>
    {proposal&&<div role="status" className="space-y-3 rounded-xl border border-amber-500/50 p-5"><h4 className="font-bold">应用“{SITE_PRESETS[selected].label}”前确认</h4><p className="text-sm">导航：{config.navigation.filter(item=>item.visible).map(item=>item.label).join(' / ')||'无'} → {proposal.navigation.filter(item=>item.visible).map(item=>item.label).join(' / ')}</p><p className="text-sm">首页模块：{home.modules.map(key=>HOME_MODULE_LABELS[key]).join(' / ')||'无'} → {proposal.home.modules.map(key=>HOME_MODULE_LABELS[key]).join(' / ')}</p><p className="text-sm">首屏标题将改为“{proposal.home.heroTitle}”；现有自定义页面与外部链接继续保留，导航最多8项。应用后仍需保存草稿并发布。</p><button onClick={()=>{onChange(proposal);setSelected(null);}} className="rounded-lg bg-teal-600 px-4 py-2 text-white">应用到编辑中的草稿</button><button onClick={()=>setSelected(null)} className="ml-4">取消</button></div>}
    <div className="space-y-3"><h3 className="font-bold">首页模块与顺序</h3><p className="text-sm text-slate-400">两套主题均读取此配置。论坛未启用时，文章模块自动隐藏；广告还需在广告设置中启用并填写内容。</p>{home.modules.map((key,index)=><div key={key} className="flex items-center gap-4 rounded-lg border border-slate-600 p-3"><span className="w-7 text-slate-400">{index+1}</span><strong className="flex-1 text-sm">{HOME_MODULE_LABELS[key]}</strong><button disabled={index===0} aria-label={`上移${HOME_MODULE_LABELS[key]}`} onClick={()=>move(index,-1)} className="disabled:opacity-30">↑</button><button disabled={index===home.modules.length-1} aria-label={`下移${HOME_MODULE_LABELS[key]}`} onClick={()=>move(index,1)} className="disabled:opacity-30">↓</button><button onClick={()=>change('modules',home.modules.filter(item=>item!==key))} className="text-rose-400">关闭</button></div>)}<div className="flex gap-3">{HOME_MODULES.filter(key=>!home.modules.includes(key)).map(key=><button key={key} onClick={()=>change('modules',[...home.modules,key])} className="rounded-lg border border-teal-600 p-2 text-sm">启用 {HOME_MODULE_LABELS[key]}</button>)}</div></div>
    <div className="grid grid-cols-2 gap-5">{[['heroTitle','首屏标题',80],['heroDescription','首屏说明',300],['heroKicker','首屏小标题',100],['featuredTitle','精选模块标题',80],['articlesTitle','文章模块标题',80]].map(([key,label,max])=><label key={key} className="text-sm">{label}<input className={control} maxLength={max} value={home[key]} onChange={event=>change(key,event.target.value)}/></label>)}<label className="text-sm">首屏主要操作<select className={control} value={home.heroAction} onChange={event=>change('heroAction',event.target.value)}><option value="market">浏览商品</option><option value="points">赚取积分</option><option value="none">不显示操作按钮</option></select></label>{[['articleCount','文章数量',1,12],['rotationSeconds','轮播间隔（秒）',3,60]].map(([key,label,min,max])=><label key={key} className="text-sm">{label}<input type="number" className={control} min={min} max={max} value={home[key]} onChange={event=>change(key,Number(event.target.value))}/></label>)}</div>
    <div className="flex gap-6">{[['showJourney','显示 TMGM 任务与兑换引导'],['showPublish','显示首屏发布按钮'],['showLead','显示首屏精选商品'],['autoRotate','自动轮播']].map(([key,label])=><label key={key} className="text-sm"><input type="checkbox" checked={home[key]} onChange={event=>change(key,event.target.checked)}/> {label}</label>)}</div>
    <button onClick={()=>setPreview(value=>!value)} className="rounded-lg border border-teal-600 p-3">{preview?'收起':'展开'}清爽主题首页预览</button>
    {preview&&<div data-design="editorial" className="max-h-[700px] overflow-auto rounded-xl border border-slate-600"><p className="p-4 text-sm">编辑中预览，尚未发布；使用本地真实商品，论坛文章数据未加载。</p><div inert><EditorialHome siteSettings={{...settings,siteBrand:config,siteName:config.name}} products={products} forumPosts={[]} setRoute={()=>{}} setAuthModal={()=>{}} openPostDetail={()=>{}} t={zh=>zh}/></div></div>}
  </div>;
}
