"use client";

import { useCallback, useEffect, useState } from 'react';
import { apiFetch } from '@/lib/api-client';
import { useInteraction } from '@/app/components/ui/UiKit';

const fieldClass='w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white';

export default function PointsAdmin(){
  const {confirmAction,requestInput}=useInteraction();
  const [data,setData]=useState(null);
  const [notice,setNotice]=useState('');
  const [busy,setBusy]=useState(false);
  const [drafts,setDrafts]=useState({});
  const [custom,setCustom]=useState({title:'',description:'',rewardPoints:10,targetUrl:'',proofLabel:'核验信息',enabled:true});
  const load=useCallback(async()=>{const response=await apiFetch('/api/points/admin',{cache:'no-store'});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.message||'载入失败');setData(result);setDrafts(Object.fromEntries(result.tasks.map(task=>[task.id,{...task,enabled:Boolean(task.enabled)}])));},[]);
  // Load the administrator-only task catalog after the panel mounts.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{load().catch(error=>setNotice(error.message));},[load]);
  const send=async(body)=>{setBusy(true);setNotice('');try{const response=await apiFetch('/api/points/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.message||'保存失败');await load();setNotice('已保存');return true;}catch(error){setNotice(error.message);return false;}finally{setBusy(false);}};
  const taskField=(taskId,key,value)=>setDrafts(previous=>({...previous,[taskId]:{...previous[taskId],[key]:value}}));
  const saveTask=task=>{const current=drafts[task.id];return send({action:'update_task',taskId:task.id,title:current.title,description:current.description,rewardPoints:Number(current.rewardPoints),targetUrl:current.targetUrl||'',proofLabel:current.proofLabel||'',enabled:Boolean(current.enabled)});};
  const pending=data?.claims.filter(claim=>claim.status==='pending')||[];
  const decide=async(claim,approve)=>{
    if(approve){if(!await confirmAction({title:'核实并发放积分',description:`${claim.username} · ${claim.taskTitle}`,noticeTitle:'请先独立核实任务完成情况',notice:'TMGM 入金需在广告商后台核对客户 ID 和实际入金；社交任务需核对真实关注或入群。',confirmLabel:'已核实，发放积分'}))return;await send({action:'review_claim',claimId:claim.id,approve:true,note:''});return;}
    const note=await requestInput({title:'驳回积分任务',description:`${claim.username} · ${claim.taskTitle}`,label:'驳回原因',required:true,minLength:3,maxLength:500,multiline:true,confirmLabel:'确认驳回'});
    if(note)await send({action:'review_claim',claimId:claim.id,approve:false,note});
  };
  if (!data) return <section className="rounded-xl border border-slate-700 p-5" aria-busy={!notice}>{notice ? <><p role="alert">{notice}</p><button className="mt-4 rounded-lg bg-cyan-600 px-4 py-2 text-white" onClick={()=>{setNotice('');load().catch(error=>setNotice(error.message));}}>重新读取积分任务</button></> : <p role="status">正在读取积分任务与审核记录…</p>}</section>;
  return <div className="space-y-6 pb-20 text-slate-200">
    <div className="rounded-xl border border-cyan-500/25 bg-cyan-500/5 p-4 text-sm leading-6">管理员可逐项设置任务奖励。策略积分价由发布者在发布或编辑 EA 时填写。TMGM 入金、X 关注及 Telegram 入群需核实后批准。积分充值仍关闭；这些积分不会计入现金收入或创作者分成。</div>
    {notice&&<p role="status" className="rounded-lg border border-slate-700 p-3 text-sm">{notice}</p>}
    <section className="rounded-xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="text-lg font-bold text-white">待审核任务 <span className="text-amber-300">{pending.length}</span></h2><div className="mt-4 space-y-3">{pending.length?pending.map(claim=><div key={claim.id} className="rounded-lg border border-slate-700 bg-slate-950 p-4 text-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong className="text-white">{claim.username} · {claim.taskTitle}</strong><p className="mt-2 break-all text-slate-400">注册邮箱：{claim.contactEmail||'—'} · 客户 ID：{claim.customerId||'—'} · 证明：{claim.proofText||'—'}</p></div><div className="flex gap-2"><button disabled={busy} onClick={()=>decide(claim,false)} className="rounded-lg border border-red-500/40 px-3 py-2 text-red-300 disabled:opacity-50">驳回</button><button disabled={busy} onClick={()=>decide(claim,true)} className="rounded-lg bg-emerald-600 px-3 py-2 font-semibold text-white disabled:opacity-50">核实并发放</button></div></div></div>):<p className="text-sm text-slate-500">目前没有待审核记录</p>}</div></section>
    <section className="rounded-xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="text-lg font-bold text-white">任务奖励设置</h2><div className="mt-4 grid gap-4 xl:grid-cols-2">{data?.tasks.map(task=>{const draft=drafts[task.id];if(!draft)return null;return <div key={task.id} className="space-y-3 rounded-lg border border-slate-700 bg-slate-950 p-4"><div className="flex items-center justify-between gap-3"><span className="text-xs text-slate-500">{task.code} · {task.cadence==='daily'?'每日':'一次性'} · {task.reviewMode==='manual'?'人工审核':'自动发放'}</span><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.enabled} onChange={event=>taskField(task.id,'enabled',event.target.checked)}/>开启</label></div><input aria-label="任务标题" className={fieldClass} value={draft.title} maxLength={100} onChange={event=>taskField(task.id,'title',event.target.value)}/><textarea aria-label="任务说明" className={fieldClass} value={draft.description} maxLength={500} onChange={event=>taskField(task.id,'description',event.target.value)}/><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-400">奖励积分<input type="number" min="0" max="1000000" className={`${fieldClass} mt-1`} value={draft.rewardPoints} onChange={event=>taskField(task.id,'rewardPoints',event.target.value)}/></label><label className="text-xs text-slate-400">证明字段提示<input className={`${fieldClass} mt-1`} value={draft.proofLabel||''} onChange={event=>taskField(task.id,'proofLabel',event.target.value)}/></label></div><label className="block text-xs text-slate-400">任务链接（留空时 X、Telegram、TMGM 使用现有站点链接）<input type="url" className={`${fieldClass} mt-1`} value={draft.targetUrl||''} onChange={event=>taskField(task.id,'targetUrl',event.target.value)}/></label><button disabled={busy} onClick={()=>saveTask(task)} className="rounded-lg bg-cyan-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">保存任务</button></div>;})}</div></section>
    <section className="rounded-xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="text-lg font-bold text-white">新增自定义任务</h2><p className="mt-2 text-sm text-slate-400">自定义任务为一次性、管理员审核；后续可关闭或修改奖励。</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><input className={fieldClass} placeholder="任务标题" value={custom.title} onChange={event=>setCustom({...custom,title:event.target.value})}/><input className={fieldClass} placeholder="核验信息提示" value={custom.proofLabel} onChange={event=>setCustom({...custom,proofLabel:event.target.value})}/><textarea className={fieldClass} placeholder="任务说明" value={custom.description} onChange={event=>setCustom({...custom,description:event.target.value})}/><div className="space-y-3"><input type="number" min="0" max="1000000" className={fieldClass} placeholder="奖励积分" value={custom.rewardPoints} onChange={event=>setCustom({...custom,rewardPoints:event.target.value})}/><input type="url" className={fieldClass} placeholder="https://任务链接（可选）" value={custom.targetUrl} onChange={event=>setCustom({...custom,targetUrl:event.target.value})}/></div></div><button disabled={busy} onClick={async()=>{if(await send({action:'create_task',...custom,rewardPoints:Number(custom.rewardPoints)}))setCustom({title:'',description:'',rewardPoints:10,targetUrl:'',proofLabel:'核验信息',enabled:true});}} className="mt-4 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">创建任务</button></section>
  </div>;
}
