import { withApiErrors } from '@/lib/api-errors';
import {NextResponse} from 'next/server';
import {getSessionUser} from '@/lib/auth';
import {createReportSchema,parseJson,resolveReportSchema} from '@/lib/validation';
import {createContentReport,listContentReports,resolveContentReport} from '@/lib/content-moderation';
import {createSecurityContext,enforceRateLimits,RATE_LIMITS,withAudit} from '@/lib/security';
export const dynamic='force-dynamic';
async function GETHandler(request){const user=await getSessionUser(),context=createSecurityContext(request,user);const audited=(response,outcome,reasonCode,metadata={})=>withAudit(context,response,{eventType:'report.read',outcome,reasonCode,targetType:'report',metadata});if(user?.role!=='admin')return audited(NextResponse.json({success:false,message:'仅管理员可查看举报'},{status:user?403:401}),'failure','FORBIDDEN');const status=new URL(request.url).searchParams.get('status')||'pending';if(!['pending','dismissed','confirmed'].includes(status))return audited(NextResponse.json({success:false,message:'举报状态不合法'},{status:400}),'failure','VALIDATION_ERROR');return audited(NextResponse.json({success:true,reports:listContentReports(status)}),'success','LISTED',{status});}
async function POSTHandler(request){const user=await getSessionUser(),context=createSecurityContext(request,user);const audited=(response,outcome,reasonCode,targetId=null,metadata={})=>withAudit(context,response,{eventType:'report.create',outcome,reasonCode,targetType:'report',targetId,metadata});const limited=enforceRateLimits(context,'report.create',[{policy:RATE_LIMITS.reportWrite,identifier:user?`user:${user.id}`:context.sourceHash}]);if(limited)return limited;if(!user)return audited(NextResponse.json({success:false,message:'请先登录'},{status:401}),'failure','UNAUTHENTICATED');const parsed=await parseJson(request,createReportSchema);if(!parsed.success)return audited(parsed.response,'failure','VALIDATION_ERROR');try{const report=createContentReport(user.id,parsed.data);return audited(NextResponse.json({success:true,report},{status:report.replayed?200:201}),'success',report.replayed?'REPLAYED':'CREATED',report.id,{targetType:parsed.data.targetType,targetId:parsed.data.targetId});}catch(error){const known={TARGET_NOT_FOUND:['内容不存在或已被隐藏',404],SELF_REPORT:['不能举报自己发布的内容',409]};if(known[error.message]){const[message,status]=known[error.message];return audited(NextResponse.json({success:false,message},{status}),'failure',error.message);}if(error.code==='SQLITE_CONSTRAINT_UNIQUE')return audited(NextResponse.json({success:false,message:'该内容已有待处理举报'},{status:409}),'failure','DUPLICATE');return audited(NextResponse.json({success:false,message:'举报提交失败'},{status:500}),'failure','INTERNAL_ERROR');}}
async function PATCHHandler(request){const user=await getSessionUser(),context=createSecurityContext(request,user);const audited=(response,outcome,reasonCode,targetId=null,metadata={})=>withAudit(context,response,{eventType:'report.resolve',outcome,reasonCode,targetType:'report',targetId,metadata});const limited=enforceRateLimits(context,'report.resolve',[{policy:RATE_LIMITS.reportAdmin,identifier:user?`user:${user.id}`:context.sourceHash}]);if(limited)return limited;if(user?.role!=='admin')return audited(NextResponse.json({success:false,message:'仅管理员可处置举报'},{status:user?403:401}),'failure','FORBIDDEN');const parsed=await parseJson(request,resolveReportSchema);if(!parsed.success)return audited(parsed.response,'failure','VALIDATION_ERROR');try{const result=resolveContentReport(parsed.data.id,parsed.data.decision,parsed.data.note,user.id);return audited(NextResponse.json({success:true,result}),'success',result.replayed?'REPLAYED':result.status.toUpperCase(),result.id,{decision:parsed.data.decision});}catch(error){const known={REPORT_NOT_FOUND:['举报不存在',404],TARGET_NOT_FOUND:['目标内容不存在',404]};if(!known[error.message])throw error;const[message,status]=known[error.message];return audited(NextResponse.json({success:false,message},{status}),'failure',error.message,parsed.data.id);}}

export const GET = withApiErrors(GETHandler, { route: '/api/reports' });
export const POST = withApiErrors(POSTHandler, { route: '/api/reports' });
export const PATCH = withApiErrors(PATCHHandler, { route: '/api/reports' });
